### ISSUE TITLE
Direct write from `sf` to GDB - Esri Contribution to OpenFileGDB

### ISSUE THREAD

**Issue by jacksonvoelkel** [R-ArcGIS/r-bridge-install#102]
Is it possible for Esri to contribute a GDB writer to the OpenFileGDB driver? 99.99% of the time people will have this driver installed, but it will not allow direct writing to a .gdb. 

I know you provide some tools to "directly" write to a gdb, but these are just creating temp shapefiles and copying them in. This added complexity is prone to errors, and a much more intelligent solution would be to simply allow GDAL (and by extension R and `sf`) to write to a .gdb.

**Comment by scdub** [comment]
@jacksonvoelkel There are three paths to work with FileGDB in R:

Tool | read | write | notes
----|------|------|------
`arcgisbinding` | ☑  | ☑  | ArcGIS installation [as described in prerequsites](https://github.com/R-ArcGIS/r-bridge-install#prerequisites)
[OpenFileGDB GDAL driver](https://gdal.org/drivers/vector/openfilegdb.html) | ☑ |  🔲  | clean room implementation [described here](https://github.com/rouault/dump_gdbtable/wiki/FGDB-Spec)
[FileGDB GDAL driver](https://gdal.org/drivers/vector/filegdb.html#vector-filegdb) | ☑ | ☑ | Requires FileGDB API SDK installation

This package is the first in the list above, and uses the native implementation Esri software provides to work with FileGDBs which we support. The other two paths use GDAL, and if you want to work through GDAL with writing FileGDBs, you can install the FileGDB API and use it that way. If you want to see the OpenFileGDB implementation gain full write support, that's something you should bring up with the GDAL developers as an enhancement request &mdash; it definitely would be a nice addition.
