### ISSUE TITLE
package ‘arcgisbinding’ is not available as a binary package for R 4.1

### ISSUE THREAD

**Issue by chinhqho** [R-ArcGIS/r-bridge-install#103]
Has newest version of R 4.1.1 broken "arcgisbinding".
When I run this following script using R 32 bit to connect R with ArcGIS Desktop 10.7:
install.packages("arcgisbinding", repos="http://r-arcgis.github.io/r-bridge", type="win.binary")
I got the error, which said:package ‘arcgisbinding’ is not available as a binary package for this version of R

platform       i386-w64-mingw32            
arch           i386                        
os             mingw32                     
system         i386, mingw32               
status                                     
major          4                           
minor          1.1                         
year           2021                        
month          08                          
day            10                          
svn rev        80725                       
language       R                           
version.string R version 4.1.1 (2021-08-10)
nickname       Kick Things

**Comment by scdub** [comment]
The correct `repos` path to use is now `r.esri.com`, this should work:

```r
install.packages("arcgisbinding", repos="https://r.esri.com", type="win.binary")
```
