### ISSUE TITLE
Error: Could not bind to a valid ArcGIS Pro installation (ArcGIS 10.7 and R 4.0.0)

### ISSUE THREAD

**Issue by merritbn** [R-ArcGIS/r-bridge-install#104]
Hello, 
I have been trying to get the ArcBridge running but while Arc can see R, I cannot seem to get the bridge to work in R. I followed suggestions in Issue #64, and can successfully run Progress Messages from the Catalog - it counts up and counts back down; however, I still cannot seem to bind. Any suggestions are greatly appreciated.

**Comment by orhuna** [comment]
Hello, @merritbn. What is the version of R, and Desktop/Pro are you using? Are you using a 32 bit or a 64-bit version of R?

**Comment by merritbn** [comment]
Hi @orhuna, 
I am running R vers 4.0.0 and ArcGIS 10.8.1. I just upgraded from 10.7 but still cannot get the bridge to connect. Both programs are running on a 64-bit framework.

**Comment by orhuna** [comment]
@merritbn thanks for the details above. The issue is the 64-bit version of R. `arcgisbinding` require 32-bit R to bind to Desktop. Installing a 32-bit R version will fix this issue.

**Comment by merritbn** [comment]
@orhuna, 
Thank you for clarifying. I flipped over to the 32-bit build and we are in business! Thanks for your time!
