### ISSUE TITLE
R 64-bit vs Arcmap 32-bit

### ISSUE THREAD

**Issue by username272727** [R-ArcGIS/r-bridge-install#106]
Hi,

I succesfully installed the background geoprocessing extension and the bridge in arcmap 10.6 as instructed in the [tutorial](https://highered-esricanada.github.io/r-arcgis-tutorials/1-Getting-Started.pdf).

My problem is that when I run the arc.check_product() command, I get this message: 

Error: Could not bind to a valid ArcGIS Pro installation.
Found ArcGIS Desktop (32-bit) Version 10.6.9270.
You'll need to use the 32-bit version of R.

**I can't run arcmap 32-bits through R 64-bits, even after installing background geoprocessing and R bridge. Is the use of R 32-bits mandatory? Is there a way to get around this issue? I thought that this was background geoprocessing's reason to exist.**

Thank you

**Comment by scdub** [comment]
Hello @username272727, 

Unfortunately, it is not possible on Windows for a 64-bit process to load 32-bit DLLs, which would be required when going from 64-bit R to the ArcGIS Desktop installation. We tried to lay this out in the [prerequisites section](https://github.com/R-ArcGIS/r-bridge-install#prerequisites) of the README, definitely open to suggestions on how to make this more clear. The background geoprocessing does allow you to create R script tools and have them executed against 64-bit R, so for example if you wrapped your functionality in a tool, it can call 64-bit R as covered in Section E of the tutorial you're following and illustrated with tools from the [r-sample-tools repository](https://github.com/R-ArcGIS/r-sample-tools). The other option if available to you is to use ArcGIS Pro which is a native 64-bit application and only works with 64-bit R.
