### ISSUE TITLE
r-bridge-install in arcmap10.7 

### ISSUE THREAD

**Issue by Autismht** [R-ArcGIS/r-bridge-install#107]
Installing r-bridge-install in arcmap10.7 shows success, but calling in R shows "library(arcgisbinding)
*** Please call arc.check_product() to define a desktop license.”

**Comment by orhuna** [comment]
@Autismht yes, when importing `arcgisbinding` a necessary second step is running
`arc.check_product()`

This function will bind `arcgisbinding` to the active ArcGIS license and will active all package functions for use. Note that without successful run of this function you will not be able to use any `arcgisbinding` functions.

**Comment by Autismht** [comment]
> @Autismht是的，导入`arcgisbinding`必要的第二步时正在运行 `arc.check_product()`
> 
> 此功能将绑定`arcgisbinding`到活动的 ArcGIS 许可，并将激活所有包功能以供使用。请注意，如果没有成功运行此功能，您将无法使用任何`arcgisbinding`功能。

When I use arc.check_product(),it shows this.
FNP preptool has not been run on this executable

**Comment by scdub** [comment]
Can you try repairing your ArcGIS installation? From Control Panel, if you visit Add / Remove programs, select ArcGIS Desktop 10.7, then click the uninstall button, you should see a dialog which lets you select repair:

![image](https://user-images.githubusercontent.com/46331011/159104242-ee30e71e-591b-47a2-8630-4dad5a3a9654.png)

**Comment by orhuna** [comment]
@Autismht in addition to @scdub 's suggestion above make sure that when you launch your ArcGIS Desktop it is connected to a license. when `arc.check_product()` is run, it queries the active license attached to ArcGIS Desktop. If you installed ArcGIS Desktop but not checkout a license, you will still see this error message.

**Comment by orhuna** [comment]
No follow-up. Closing issue.
