### ISSUE TITLE
Install R bindings failed 

### ISSUE THREAD

**Issue by miaforsline** [R-ArcGIS/r-bridge-install#113]
Hello, 

I am running ArcPro 3.0.0 and R 4.2.2 on a work computer using Windows 10. I have successfully installed the `arcgisbinding `package in R and loaded the` R Integration.pyt` toolbox into ArcPro. 

![image](https://user-images.githubusercontent.com/88208710/208470570-1066f9b6-f3b4-422b-9a9d-0de197661f3c.png)

I have also successfully connected R to ArcPro, so the Print R Version script runs and tells me what version of R I am using: 

![image](https://user-images.githubusercontent.com/88208710/208470358-d9c24e2a-3566-4b98-af95-2853e229e039.png)

However, I cannot get the `Install R bindings` script to run due to the following error: 

![image](https://user-images.githubusercontent.com/88208710/208470911-d5b724e7-6b5b-480c-bf86-5298c124eb83.png)

Has anyone else run into a similar issue? I'm wondering if this SSL issue is related to me working on a company computer with security settings I don't know about. 

Thank you.

**Comment by scdub** [comment]
@miaforsline Thanks for your report. This package is still using the old approach to installing the package, and that is showing up in your environment when it tries to contact GitHub. That said, you can safely ignore it &mdash; you did successfully install the package as shown in your earlier screenshot. It should work from Pro and from 64-bit R as-is, I will address the release information but this installer is mostly for older releases of ArcMap and the UI is the right way to go for Pro.

Hello from another master's UCSB alumnus! I was in the Gaines lab, graduated 2013.

**Comment by miaforsline** [comment]
@scdub 

Thank you for your prompt response! Yes, you're correct. Despite the warning I was getting from the script, I am able to use the R-ArcGIS Bridge with no problems. 

Thank you again :) It's always nice to connect with fellow UCSB alum. Happy holidays !
