### ISSUE TITLE
not working with R 4.3.0

### ISSUE THREAD

**Issue by victoriadancoMNRF** [R-ArcGIS/r-bridge-install#117]
I am having an issue with trying to install R bindings with ArcGIS 10.3.1 and R 4.3.0 
![image](https://user-images.githubusercontent.com/60553399/235732931-ad6bf222-731a-4f9b-aa89-2bfdfecb1863.png)

ERROR traceback (most recent call last): File "", line 221, in updateParameters File "", line 260, in g_rversion_param Key Error : u'4.3.0'

**Comment by JosiahParry** [comment]
Duplicate of R-ArcGIS/r-bridge#81
