### ISSUE TITLE
Question about rarcproxy.dll

### ISSUE THREAD

**Issue by DJSherwood** [R-ArcGIS/r-bridge-install#13]
Greetings!

I really like the idea of having ready access to the R program through ArcGIS. Unfortunately, I am having a problem which I hope has a straightforward solution.  

I installed the "arcgisbinding" package for R and get the correct build number for the version of ArcGIS I use (10.3.1). The output from arc.check_product() says "binding dll: rarcproxy." When I run the "R Installation Details" script from within ArcGIS, I receive the correct version of R (3.2.1) in the correct location (H:\R\R-3.2.1\). 

But when I attempt to run the semiparametric regression tool (I obtained it from here: https://github.com/R-ArcGIS/r-sample-tools), I receive the error:

Start Time: Wed Dec 02 14:02:52 2015
Running script SemiparametricRegression...
Cannot find 'rarcproxy.dll'.
Plese install Rintegration package.
Failed to execute (SemiparametricRegression).

Is there a way that I can troubleshoot this problem? The two programs seem to see each other, but the error suggests otherwise. 

Thank you for your time!

**Comment by dpavlushko** [comment]
Please check if following folders are exist - C:\Program Files (x86)\ArcGIS\Desktop10.3\Rintegration\arcgisbinding
"arcgisbinding" folder should be symbolic link to C:\Users\<USER>\Documents\R\win-library\3.2\arcgisbinding (or H:\R\R-3.2.1\library\arcgisbinding)
If folder structure is not correct find and delete  "arcgisbinding" directory, then re-install R bridge.

**Comment by DJSherwood** [comment]
Thank you!

I attempted several things, and in the process destroyed my progress. I've
started over:

    * The R-Bridge (unzipped from the repository) is within C:\Program
Files (x86)\ArcGIS\Desktop10.3\Rintegration .
    * The library "arcgisbinding" is within C:\Program
Files\R\R-3.2.1\library .
    * arc.check_product() (using the above mentioned version of R) gives
ArcGIS desktop (10.3.1.4959) and mentions "binding dll: rarcprocxy."
    * But "Install R Bindings" says"Unable to find valid R installation.
Please Install R."

Where does the "install R bindings" script expect to find the R executable?
Perhaps this is a problem with my registry?
What should I look for to determine if it is?

Thank you for your time and patience!

On Wed, Dec 2, 2015 at 8:23 PM, Dmitry Pavlushko <notifications@github.com>
wrote:

> Please check if following folders are exist - C:\Program Files
> (x86)\ArcGIS\Desktop10.3\Rintegration\arcgisbinding
> "arcgisbinding" folder should be symbolic link to
> C:\Users<USER>\Documents\R\win-library\3.2\arcgisbinding (or
> H:\R\R-3.2.1\library\arcgisbinding)
> If folder structure is not correct find and delete "arcgisbinding"
> directory, then re-install R bridge.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/R-ArcGIS/r-bridge-install/issues/13#issuecomment-161496610>
> .
>



-- 
Daniel J. Sherwood
(830) 765-3650

**Comment by dpavlushko** [comment]
I assume you are making manual install. 
You need to make symbolic link from regular R packages directory to ArcGIS\Desktop10.3\Rintegration
Open command prompt (cmd.exe) and execute this line:
<code>mklink /J "C:\Program Files (x86)\ArcGIS\Desktop10.3\Rintegration\arcgisbinding" "C:\Program Files\R\R-3.2.1\library\arcgisbinding"</code>

**Comment by DJSherwood** [comment]
I managed to make it work. The R-bridge kept focusing on my version of R
installed on my H:/ drive. In the end, I had to uninstall R everywhere, and
then re-install it on C:/.

Thank you for your help. I think this will be quite fun.

On Thu, Dec 3, 2015 at 6:47 PM, Dmitry Pavlushko <notifications@github.com>
wrote:

> I assume you are making manual install.
> You need to make symbolic link from regular R packages directory to
> ArcGIS\Desktop10.3\Rintegration
> Open command prompt (cmd.exe) and execute this line:
> mklink /J "C:\Program Files
> (x86)\ArcGIS\Desktop10.3\Rintegration\arcgisbinding" "C:\Program
> Files\R\R-3.2.1\library\arcgisbinding"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/R-ArcGIS/r-bridge-install/issues/13#issuecomment-161839187>
> .
>



-- 
Daniel J. Sherwood
(830) 765-3650

**Comment by scw** [comment]
@DJSherwood, glad you got this to work for you. By default, our installer looks into the registry to determine the R installation. In the case of multiple installations, it may locate a different version than the one you intended to use -- by default, we use the newest install. Unfortunately, we do have to chose a single install and it can be confusing on machines with multiple installations of R.
