### ISSUE TITLE
does r-bridge support arcgis desktop 10.4 and arcgis pro 1.2?

### ISSUE THREAD

**Issue by crazyxhz** [R-ArcGIS/r-bridge-install#16]
does r-bridge support arcgis desktop 10.4 and arcgis pro 1.2?

**Comment by dpavlushko** [comment]
All recent releases Desktop 10.4 and Pro 1.3 are supported.

**Comment by scw** [comment]
Hello @crazyxhz, as Dmitry mentioned the bridge will work with both 10.4 and ArcGIS Pro 1.2. I've updated the requirements section to make this clear. Let us know if you run into any issues, and feel free to open a new issue.
