### ISSUE TITLE
Need help with arcgisbinding in R

### ISSUE THREAD

**Issue by pieterz** [R-ArcGIS/r-bridge-install#17]
Hi,

I am trying to use the arcgisbinding package in R to make a tool for arcgis, but it is not working. The r-bridge-install-master went well in arcmap. The R Script Examples toolbar worked also very good in arcma. When I used the qqplots it returned 4 plots from R in arcmap. But when I tried to check if the arcgis binding package in R had the right license i got an error in R. 

When:
>library(arcgisbinding)
>arc.check_product()

R returns 
![error](https://cloud.githubusercontent.com/assets/18269076/14258147/64cefce2-faa1-11e5-9340-c4ca25468b6b.png)

R version 3.2.4 and arcgisbinding is shown as package in R
ArcMap version 10.4

hopefully somebody can help me with this problem.

With kind regards,

Pieter

**Comment by scw** [comment]
Pieter,

Sorry to hear about this issue. Could you try running the same code from a standard R session? It should produce an error with more information than RStudio is currently displaying. If so, could you post that information here?

Also for the purposes of reproduction, could you let us know what version of RStudio you're using, and what OS?

Thanks,
Shaun

**Comment by pieterz** [comment]
Version 0.99.484 – © 2009-2015 RStudio, Inc.
Windows 10
I also use a trial version of arcmap 10.4

after entering the command i immediately get this error and shuts down R:
_R for Windows GUI front-end is not working anymore_

Somebody with the same problem:
https://github.com/R-ArcGIS/r-bridge/issues/3

**Comment by pieterz** [comment]
Could this be due the fact that i only have 4 gb RAM on my computer?

**Comment by scw** [comment]
Thanks for the details. Memory shouldn't be an issue, I'll work on trying to recreate this issue in a test environment.

Cheers,
Shaun

**Comment by pieterz** [comment]
Thank you very much! :)

**Comment by scw** [comment]
Hi @pieterz,

Would you be able to try the new release of R, 3.2.5, and see if it eliminates the problem? It can [be downloaded](https://cloud.r-project.org/bin/windows/base/) from the R site.

**Comment by pieterz** [comment]
Dear Shaun,

I tried it on the new R version but unfortunately i get the same error.

**Comment by scw** [comment]
@pieterz, sorry for the delay.

I set up a machine running Windows 10 (x64), ArcGIS 10.4, and R 3.2.5. Unfortunately, I can't seem to reproduce the issue -- R looks to work fine from both ArcMap, and from the R prompt. Note that it will only work by default from a 32-bit R session, but it should give you a notice that it can't find ArcGIS in the 64-bit R environment, not crash. Could you post a screenshot of your licensing availability? Here's what it looks like when I created a trial account for testing:

![screen shot 2016-04-21 at 4 29 37 pm](https://cloud.githubusercontent.com/assets/1314/14731646/c5be2726-0820-11e6-9e77-d13940296dad.png)

**Comment by pieterz** [comment]
Dear Shaun,

When i uninstalled R 3.2.4 revised i also did this for my Rstudio version. After I installed R 3.2.5 and Rstudio I forgot to change the default setting to 32 bits. I am now getting the right reponse!

Thank you for your helping me!

With kind regards,
Pieter

**Comment by scw** [comment]
Great! Glad this is working. We'll have to document the issues from R studio, which can make it less clear which version of R is running.

Cheers,
Shaun
