### ISSUE TITLE
C:\Program' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by rswettiii** [R-ArcGIS/r-bridge-install#18]
I installed on my laptop no problem, but on my desktop (trying in both ArcGIS Pro 1.2 and ArcMap 10.4, run as Administrator) I get the message below:

Messages
Start Time: Tue Apr 05 13:50:13 2016
Running script InstallBindings...
Saving URL to '**C:\Users\rswett\AppData\Local\Temp\ArcGISPro6804\tmpmg4a5rna\arcgisbinding_1.0.0.118.zip'
! 'C:\Program' is not recognized as an internal or external command,**
! operable program or batch file.
! R command returned non-zero exit status.
Completed script InstallBindings...
Succeeded at Tue Apr 05 13:50:16 2016 (Elapsed Time: 2.85 seconds)

**Comment by scw** [comment]
@rswettiii thanks for the report. Could you download the bridge again and run the command a second time? I've added an additional message that should include the exact command run which will help me understand the nature of the issue.

Thanks,
Shaun

**Comment by rswettiii** [comment]
Shaun, below is the new message:

Messages
Start Time: Tue Apr 05 14:52:36 2016
Running script InstallBindings...
Saving URL to 'C:\Users\rswett\AppData\Local\Temp\ArcGISPro664\tmpof2smdhe\arcgisbinding_1.0.0.118.zip'
"C:\Program Files\R\R-3.2.4revised\bin\x64\Rcmd.exe" INSTALL C:\Users\rswett\AppData\Local\Temp\ArcGISPro664\tmpof2smdhe\arcgisbinding_1.0.0.118.zip
 'C:\Program' is not recognized as an internal or external command,
 operable program or batch file.
 R command returned non-zero exit status.
Completed script InstallBindings...
Succeeded at Tue Apr 05 14:52:39 2016 (Elapsed Time: 3.13 seconds)

**Comment by rswettiii** [comment]
Thanks. I placed the new message on github. I had accidently closed the issue, but just reopened it.

Messages
Start Time: Tue Apr 05 14:52:36 2016
Running script InstallBindings...
Saving URL to 'C:\Users\rswett\AppData\Local\Temp\ArcGISPro664\tmpof2smdhe\arcgisbinding_1.0.0.118.zip'
"C:\Program Files\R\R-3.2.4revised\bin\x64\Rcmd.exe" INSTALL C:\Users\rswett\AppData\Local\Temp\ArcGISPro664\tmpof2smdhe\arcgisbinding_1.0.0.118.zip
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
R command returned non-zero exit status.
Completed script InstallBindings...
Succeeded at Tue Apr 05 14:52:39 2016 (Elapsed Time: 3.13 seconds)

Bob Swett

**Comment by rswettiii** [comment]
I ran it from ArcMap 10.4 and got the message below:

Executing: InstallBindings false
Start Time: Tue Apr 05 16:37:07 2016
Running script InstallBindings...
Saving URL to 'c:\users\rswett\appdata\local\temp\tmpcgl720\arcgisbinding_1.0.0.118.zip'
"C:\Program Files\R\R-3.2.4revised\bin\i386\Rcmd.exe" INSTALL c:\users\rswett\appdata\local\temp\tmpcgl720\arcgisbinding_1.0.0.118.zip
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
R command returned non-zero exit status.
Completed script InstallBindings...
Succeeded at Tue Apr 05 16:37:11 2016 (Elapsed Time: 3.58 seconds)

**Comment by scw** [comment]
Hello @rswettiii, 

That's a strange issue, as the command looks correctly escaped and it generally works for folks. That said, I've made a commit which changes the path prior to attempting to execute R. Could you try it on your machine and see if it works for you?

Cheers,
Shaun

**Comment by rswettiii** [comment]
Shaun, it still didn’t work (see screenshot below). This is a university PC and the “image” was recently reinstalled after a hard drive failed. So it may be something peculiar to that process (i.e., an anomaly). The r-arcgis install works on my other desktop and laptop, so I will stick to those. Thanks for your efforts, but I don’t want to consume your time on something that may be an isolated issue.

[cid:image001.png@01D190A9.9EA9DCA0]

Bob Swett
__________________________________________________________________________­______________________
Bob Swett  |  Coordinator  |   Florida Sea Grant Boating and Waterway Planning Program   |     www.flseagrant.org<http://www.flseagrant.org/>
Associate Professor | School of Forest Resources and Conservation | Institute of Food and Agricultural Sciences–UF
PO Box 110760     |    Gainesville, FL 32611    |     •:352-392-6233    |    Fax: 352-846-1332     |     •rswett@ufl.edu<mailto:rswett@ufl.edu>

**Comment by scw** [comment]
Bob,

Thanks for trying the new build and sorry to hear it didn't resolve the issue. The screenshot didn't come through, I guess you have to attach it directly in GitHub for it to show up. One last thing you might try is another version of R -- we've had some reports of issues with 3.2.4 Revised, so your issue may go away with say 3.2.3 (or the upcoming 3.3 release once finalized). I'll mark this issue closed for now, but feel free to reopen it, or create a new issue if problems persist.

Cheers,
Shaun
