### ISSUE TITLE
Can't install R bindings

### ISSUE THREAD

**Issue by jjxsbst110** [R-ArcGIS/r-bridge-install#19]
Shows me this error massage:
"* installing to library 'D:/Users/Documents/R/win-library/3.2'
Unable to locate R package library. Link failed.
Completed script InstallBindings...
Failed to execute (InstallBindings)."
I run .libPaths() in R check my library path, gives me :
"D:/Users/Documents/R/win-library/3.2" "C:/Program Files/R/R-3.2.5/library"

**Comment by scw** [comment]
Hello @jjxsbst110,

I don't have a machine currently with the users directory hosted on another drive, could you try the "R installation details" tool and share the results? We currently check two things: 

 1. The `CSIDL_PROFILE` value, which should resolve to the users' home directory as reported by Windows. 
 2. We also check is the value of the users' `R_USER`, `R_LIBS` and `R_LIBS_SITE` environment variables.

**Comment by scw** [comment]
Hi @jjxsbst110, I've made one further change which checks the `%HOME%` variable as well. I think this may resolve your issue, could you retry the tool after downloading the latest copy?

**Comment by scw** [comment]
Issue is resolved in my tests, if it shows up again for you @jjxsbst110 feel free to reopen the issue.
