### ISSUE TITLE
Install Bindings Failure

### ISSUE THREAD

**Issue by guyn2gis** [R-ArcGIS/r-bridge-install#2]
Executing: InstallBindings false
Start Time: Tue Jul 28 18:36:46 2015
Running script InstallBindings...
https://github.com/R-ArcGIS/r-bridge/releases/download/v1.0.0.111/arcgisbinding_1.0.0.111.zip
Saving URL to 'c:\users\tcronin\appdata\local\temp\arc5412\tmpijjw4k\arcgisbinding_1.0.0.111.zip'
* installing to library 'C:/Program Files/R/R-3.1.2/library'
R command returned non-zero exit status.

Traceback (most recent call last):
  File "<string>", line 177, in execute
  File "C:\1GIS\PythonProjects\RBridge\r-bridge-install-master\rtools\install_package.py", line 99, in install_package
    os.makedirs(r_integration_dir)
  File "C:\Python27\ArcGIS10.3\Lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 5] Access is denied: u'c:\\program files (x86)\\arcgis\\desktop10.3\\Rintegration'

Failed to execute (InstallBindings).
Failed at Tue Jul 28 18:36:49 2015 (Elapsed Time: 2.17 seconds)

**Comment by guyn2gis** [comment]
Trying in Pro 1.1, I get similar results.  Above is 10.3.1.

Start Time: Tue Jul 28 18:52:27 2015
Running script InstallBindings...
Pro side by side with 10.3 detected.
https://github.com/R-ArcGIS/r-bridge/releases/download/v1.0.0.111/arcgisbinding_1.0.0.111.zip
Saving URL to 'C:\Users\tcronin\AppData\Local\Temp\ArcGISPro21380\tmpg9jg3qgr\arcgisbinding_1.0.0.111.zip'
package 'arcgisbinding' successfully unpacked and MD5 sums checked
 * installing to library 'C:/Users/tcronin/Documents/R/win-library/3.1'
Traceback (most recent call last):
  File "<string>", line 177, in execute
  File "C:\1GIS\PythonProjects\RBridge\r-bridge-install-master\rtools\install_package.py", line 99, in install_package
    os.makedirs(r_integration_dir)
  File "c:\program files\arcgis\pro\bin\Python\lib\os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Access is denied: 'c:\\program files\\arcgis\\pro\\Rintegration'
Failed to execute (InstallBindings).
Failed at Tue Jul 28 18:52:33 2015 (Elapsed Time: 6.26 seconds)

**Comment by dpavlushko** [comment]
Make sure that your user has access to create/write into c:\Program Files x86 or try to run ArcMap as an Administrator.

**Comment by guyn2gis** [comment]
Cool, running as Admin did it...

Executing: InstallBindings true
Start Time: Wed Jul 29 19:18:29 2015
Running script InstallBindings...
https://github.com/R-ArcGIS/r-bridge/releases/download/v1.0.0.111/arcgisbinding_1.0.0.111.zip
Saving URL to 'c:\users\tcronin\appdata\local\temp\arcfc21\tmpx2syjx\arcgisbinding_1.0.0.111.zip'
package 'arcgisbinding' successfully unpacked and MD5 sums checked
* installing to library 'C:/Program Files/R/R-3.1.2/library'
Detected package path: C:\Users\tcronin\Documents\R\win-library\3.1\arcgisbinding.
ArcGIS 10.3.1 detected. Creating link to package.
Completed script InstallBindings...
Succeeded at Wed Jul 29 19:18:35 2015 (Elapsed Time: 5.90 seconds)


Do I need to run the binding in Pro too?

**Comment by guyn2gis** [comment]
Any plans to link up with RStudio...

**Comment by guyn2gis** [comment]
Ran it anyway...

Start Time: Wed Jul 29 19:24:53 2015
Running script InstallBindings...
Pro side by side with 10.3 detected.
https://github.com/R-ArcGIS/r-bridge/releases/download/v1.0.0.111/arcgisbinding_1.0.0.111.zip
Saving URL to 'C:\Users\tcronin\AppData\Local\Temp\ArcGISPro6832\tmp917fg1jw\arcgisbinding_1.0.0.111.zip'
package 'arcgisbinding' successfully unpacked and MD5 sums checked
 * installing to library 'C:/Users/tcronin/Documents/R/win-library/3.1'
Detected package path: C:\Program Files\R\R-3.1.2\library\arcgisbinding.
ArcGIS 10.3.1 detected. Creating link to package.
Completed script InstallBindings...
Succeeded at Wed Jul 29 19:24:58 2015 (Elapsed Time: 4.91 seconds)

**Comment by guyn2gis** [comment]
Hopefully this is not a dumb question but are we suppose to install the C++ and the Python tools, where Python is for GP, and C++ is for the interface, or is C++ for writing C++.

**Comment by dpavlushko** [comment]
RStudio is working well with <code>arcgisbinding</code>. Just remember if you have ArcGIS 10.3.1 then setup RStudio to use 32 bit R: Menu: Tools->Options->R version click 'Change' and set "Use your machine's default version of R(32-bit)". No changes required if you have ArcGISPro (default 64-bit).

**Comment by scw** [comment]
Hello @guyn2gis, as Dima mentioned this will work fine with RStudio -- the demo we did at the UC in a technical session used RStudio. In terms of your second question, you don't need to do anything directly with the C++ ibrary -- it's automatically installed when you use the Python toolbox, and is the mechanism for ArcGIS to "talk" with R. Your code should all be able to only be R for an R script tool. We'll make further clarifications and improvements to the materials available on the web over the coming weeks.

**Comment by guyn2gis** [comment]
Will the demo be posted here from the uc?  I was in the road ahead at the time, perhaps even just the ppt.

**Comment by scw** [comment]
It'll be up on video.esri.com once the technical sessions are put up there, that generally takes at least a few weeks for all the sessions. The [short demo](http://video.esri.com/watch/4651/statistical-integration-with-r) from the UC plenary is up online now, if you'd like to check that out.

**Comment by scw** [comment]
Hi @guyn2gis, marking this as solved since you were able to get the bridge installed. Thanks for trying out the project, and I'll incorporate your ideas into the next round of fixes. Feel free to open a new issue if you have any further problems.
