### ISSUE TITLE
Can't install  R bindings

### ISSUE THREAD

**Issue by waholulu** [R-ArcGIS/r-bridge-install#22]
The report shows

> Executing: InstallBindings false
> Start Time: Mon May 30 21:33:25 2016
> Running script InstallBindings...
> Saving URL to 'c:\users\admini~1\appdata\local\temp\arc35a2\tmpbed2zc\arcgisbinding_1.0.0.118.zip'

> Traceback (most recent call last):
>   File "<string>", line 164, in execute
>   File "I:\r-bridge-install-master\rtools\install_package.py", line 214, in install_package
>     execute_r('Rcmd', 'INSTALL', package_path)
>   File "I:\r-bridge-install-master\rtools\bootstrap_r.py", line 30, in execute_r
>     os.putenv("PATH", ";".join([rcommand_dir, sys_path]))
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 944: ordinal not in range(128)
> 

> Failed to execute (InstallBindings).
> Failed at Mon May 30 21:33:28 2016 (Elapsed Time: 2.23 seconds)
>

**Comment by scw** [comment]
@waholulu I believe I've fixed this in the latest release &mdash; could you try running the installation again?
