### ISSUE TITLE
Screencast for R-side install not working

### ISSUE THREAD

**Issue by puzzledkiwi** [R-ArcGIS/r-bridge-install#23]
The screencast to manually install R-bridge from R (https://4326.us/R/zipinst/) displays as a black screen in Chrome and Firefox, under Windows 7 and Windows 10.  Are text instructions available?

Screencast.com recommends Chrome, so hoping it's not me missing some obvious plugin. 

![capture2](https://cloud.githubusercontent.com/assets/14183665/15721639/1ae6ba06-27f7-11e6-9b5a-9f22c1ae6147.PNG)

**Comment by scw** [comment]
Not sure why the embedding isn't working, but could you try [this link](https://4326.us/R/zipinst/r%20bridge%20install%20from%20zip_player.html) which is the video page itself?

**Comment by puzzledkiwi** [comment]
The screencast loads! Thank you very much - and for the quickly reply as well.

**Comment by scw** [comment]
Happy to help -- I've update the documentation to point to this location, and will take a look at the issue with the offline installation procedure in #21. Cheers, Shaun
