### ISSUE TITLE
Update R Bindings fails to execute

### ISSUE THREAD

**Issue by EconGeo** [R-ArcGIS/r-bridge-install#25]
``Running script UpdateBindings...
Traceback (most recent call last):
  File "<string>", line 47, in execute
  File "~\Downloads\r-bridge-install-master\r-bridge-install-master\rtools\update_package.py", line 28, in update_package
    validate_environment()
TypeError: validate_environment() missing 1 required positional argument: 'overwrite'
Failed to execute `(UpdateBindings).``

MRO 3.2.5, had to run Arc Pro as administrator, but also successfully installed downloading the R package as well.

And one other question, is this just installing an R package, or is it updating things in AcrGIS Pro with python?  If it is just installing an R package, why not just use ```devtools::install_github()``` ? This is what the manual install seems to be instructing but in a manual fashion.

**Comment by scw** [comment]
Hello @EconGeo,

Fixed the issue with updating, thanks for the report. Typically, installation will work without administrator privileges if an `R_LIBS_USER` directory is set or is included in `.libPaths()`, but it does require admin rights if installing a package into Program Files.

Good question on `devtools` &mdash; currently the package download includes prebuilt versions of the necessary DLLs, which require Visual Studio to produce. We also wanted to have something that would work for folks who are brand new to R, so they can run the sample tools and use tools others produce as a first step in learning R. That said, I think you're right that we should simplify the installation for folks who are already R savvy, it looks like ``devtools::install_url`` would do the trick with some work, I'll investigate.

**Comment by scw** [comment]
Created a new issue #27 for devtools based installation, closing this one for now but feel free to reopen if you have any further issues. Thanks!

**Comment by EconGeo** [comment]
Thanks.  I would also look into install_github.  That's where I've seen the most usage of devtools.
