### ISSUE TITLE
Allow installation via devtools

### ISSUE THREAD

**Issue by scw** [R-ArcGIS/r-bridge-install#27]
As mentioned in #25, for R users it'd be easiest to install directly from R. Investigate this option.

**Comment by dpavlushko** [comment]
`devtools` or `R CMD build/install` cannot handle all steps for building `arcgisbinding` package. To build package from source please follow ["Build from source"](https://github.com/R-ArcGIS/r-bridge#building-from-source) instruction. <p>To install [arcgisbinding from zip archive](https://github.com/R-ArcGIS/r-bridge/releases/latest) use RGui 'Menu->Packages->Install package(s) from local zip files...' command.</p>
