### ISSUE TITLE
Error while running R arcbinding script

### ISSUE THREAD

**Issue by josesevilla** [R-ArcGIS/r-bridge-install#28]
Hi there, 
I am now having the same error message  in calling rarcproxy as in https://github.com/R-ArcGIS/r-bridge-install/issues/3, 
I was following the instructioins in the course 
"_Part 1 of a two-part webinar series on integrating the statistical programming language R with Esri's ArcGIS for Desktop.

Cameron Plouffe of the Esri Canada Education and Research group covers several basic R programming concepts and manipulating data frames using Hadley Wickham's "dplyr" package, and then demonstrates how you can use the new R-ArcGIS bridge to interface directly to ArcGIS geodatabases within R.

Slide deck:http://slides.com/camplouffe/integrating-r-with-arcgis
Webinar materials: https://github.com/cplouffe/r-arcgis-webinar

Integrating R with ArcGIS (Part 2): https://www.youtube.com/watch?v=TNnCgQ-jG2I

```
Categoría
    Gente y blogs 
Licencia
    Licencia de YouTube estándar_ "
```

When going through the Part 1 video of the course, everything seemed to go ok. It is when I tried to add the R script as a tool in arctoolbox (Part 2 of the course after performing the ANOVA analysis) that I had the message:
_Executing: Script toronto_crime Drug_Arrests Population 4 C:\Users\josesevilla\Documents\ArcGIS\Default.gdb\toronto_crime_Script2 C:\Users\josesevilla\Documents\ArcGIS\Default.gdb\toronto_crime_Script3
Start Time: Mon Jul 18 10:34:08 2016
Running script Script...
Error in .Call("arc_error", msg, PACKAGE = "rarcproxy") : 
  "arc_error" not available for .Call() for package "rarcproxy"
Completed script Script...
Succeeded at Mon Jul 18 10:34:09 2016 (Elapsed Time: 1,07 seconds)_

I tried running ArcMAP as Administrator but to no avail...

**Comment by josesevilla** [comment]
running the script RVversion, I get this:
Executing: RVersion
Start Time: Mon Jul 18 12:31:47 2016
Running script RVersion...
R.exe --version
R version 3.3.1 (2016-06-21) -- "Bug in Your Hair"
Completed script RVersion...
Succeeded at Mon Jul 18 12:31:48 2016 (Elapsed Time: 1,26 seconds)

**Comment by scw** [comment]
Hello @josesevilla,

We just released a new version of the library, v121. Could you see if installing this resolves your issue?

Thanks, Shaun

**Comment by scw** [comment]
Hello @josesevilla, it's been sometime since you filed this issue, and we've released a number of new versions in the interim. If you're still having problems with the current release, let us know and we can take a look.
