### ISSUE TITLE
Error while running binding install script

### ISSUE THREAD

**Issue by dlradke** [R-ArcGIS/r-bridge-install#3]
I am trying to run the "Install R Bindings" from the "R Integration.pyt" and get the error below. I have ArcGIS 10.3.1 and R 3.2.1. I have tried the suggested troubleshooting techniques on the main github page but have had no success. It looks like it is having trouble reading the .py scripts but I could be mistaken. Is anyone else having this problem or does anyone have any suggestions on where to go from here? I've copy and pasted the details from the geoprocessing window in Arc. 

Executing: InstallBindings true
Start Time: Mon Aug 10 16:34:41 2015
Running script InstallBindings...
https://github.com/R-ArcGIS/r-bridge/releases/download/v1.0.0.111/arcgisbinding_1.0.0.111.zip
Saving URL to 'c:\users\susanr~1\appdata\local\temp\arcc146\tmpxqfp7t\arcgisbinding_1.0.0.111.zip'

Traceback (most recent call last):
  File "<string>", line 177, in execute
  File "C:\Dan\arcgisbindingR\r-bridge-install-master\rtools\install_package.py", line 77, in install_package
    execute_r('Rcmd', 'INSTALL', package_path)
  File "C:\Dan\arcgisbindingR\r-bridge-install-master\rtools\bootstrap_r.py", line 15, in execute_r
    if r_install_valid():
  File "C:\Dan\arcgisbindingR\r-bridge-install-master\rtools\bootstrap_r.py", line 71, in r_install_valid
    valid = path_exists(r_install_path)
  File "C:\Dan\arcgisbindingR\r-bridge-install-master\rtools\bootstrap_r.py", line 65, in path_exists
    if os.path.exists(path):
  File "C:\Python27\ArcGIS10.3\Lib\genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

Failed to execute (InstallBindings).
Failed at Mon Aug 10 16:34:53 2015 (Elapsed Time: 11.42 seconds)

Cheers,
Dan

**Comment by scw** [comment]
Hello @dlradke,

It looks like the script is having trouble picking up where your R installation is. Did you install R using the standard installer? Could you post the results of running the "R Installation Details" script in the toolbox?

Thanks,
Shaun

**Comment by dlradke** [comment]
Executing: RInstallDetails
Start Time: Mon Aug 10 18:34:34 2015
Running script RInstallDetails...
R not installed. Please install R prior to using
this toolbox. The R installation can be found at:
  http://www.r-project.org/

Completed script RInstallDetails...
Failed to execute (RInstallDetails).
Failed at Mon Aug 10 18:34:34 2015 (Elapsed Time: 0.01 seconds)


Looks like that may be the issue. I used the standard installer for R and its path is "C:\Program Files\R\R-3.2.1"

Dan

**Comment by scw** [comment]
OK, it looks like the detection logic for finding your R installation from the registry is failing. Could you do the following to help me debug your issue?

1. Open the Run box (Win+R) and type `regedit`
2. From the Edit > Find dialog, search the keys for the string `R-Core`, as seen here:
![screen shot 2015-08-11 at 12 58 38 am](https://cloud.githubusercontent.com/assets/1314/9190661/d0b8ae5e-3fc5-11e5-91d5-52722dc27b0a.png)
3. On my machine (64-bit), searching for that string shows two locations:
```
    HKEY_LOCAL_MACHINE\SOFTWARE\R-core
    HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\R-core
```
4. Once it finds a location, right click on the key named 'R-Core', and select export. That will create a '.reg' file, that's really just text. Attach the text contents of that file here (if possible).

Thanks!

**Comment by dlradke** [comment]
Here is the result.

Key Name:          HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\R-core
Class Name:        <NO CLASS>
Last Write Time:   8/10/2015 - 6:51 PM

Key Name:          HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\R-core\R
Class Name:        <NO CLASS>
Last Write Time:   8/10/2015 - 6:51 PM
Value 0
  Name:            InstallPath
  Type:            REG_SZ
  Data:            C:\Program Files\R\R-3.2.1

Value 1
  Name:            Current Version
  Type:            REG_SZ
  Data:            3.2.1


Key Name:          HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\R-core\R\3.2.1
Class Name:        <NO CLASS>
Last Write Time:   8/10/2015 - 6:51 PM
Value 0
  Name:            InstallPath
  Type:            REG_SZ
  Data:            C:\Program Files\R\R-3.2.1


Key Name:          HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\R-core\R32
Class Name:        <NO CLASS>
Last Write Time:   8/10/2015 - 6:51 PM
Value 0
  Name:            InstallPath
  Type:            REG_SZ
  Data:            C:\Program Files\R\R-3.2.1

Value 1
  Name:            Current Version
  Type:            REG_SZ
  Data:            3.2.1


Key Name:          HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\R-core\R32\3.2.1
Class Name:        <NO CLASS>
Last Write Time:   8/10/2015 - 6:51 PM
Value 0
  Name:            InstallPath
  Type:            REG_SZ
  Data:            C:\Program Files\R\R-3.2.1



thanks

**Comment by dlradke** [comment]
Hey Shaun,

similar to your computer, R-Core was in 2 locations. Here is the print out to the other one. 

Key Name:          HKEY_LOCAL_MACHINE\SOFTWARE\R-core
Class Name:        <NO CLASS>
Last Write Time:   8/25/2015 - 12:08 PM

Key Name:          HKEY_LOCAL_MACHINE\SOFTWARE\R-core\R
Class Name:        <NO CLASS>
Last Write Time:   8/25/2015 - 12:08 PM
Value 0
  Name:            InstallPath
  Type:            REG_SZ
  Data:            C:\Program Files\R\R-3.2.1

Value 1
  Name:            Current Version
  Type:            REG_SZ
  Data:            3.2.1


Key Name:          HKEY_LOCAL_MACHINE\SOFTWARE\R-core\R\3.2.1
Class Name:        <NO CLASS>
Last Write Time:   8/25/2015 - 12:08 PM
Value 0
  Name:            InstallPath
  Type:            REG_SZ
  Data:            C:\Program Files\R\R-3.2.1


Key Name:          HKEY_LOCAL_MACHINE\SOFTWARE\R-core\R64
Class Name:        <NO CLASS>
Last Write Time:   8/25/2015 - 12:08 PM
Value 0
  Name:            InstallPath
  Type:            REG_SZ
  Data:            C:\Program Files\R\R-3.2.1

Value 1
  Name:            Current Version
  Type:            REG_SZ
  Data:            3.2.1


Key Name:          HKEY_LOCAL_MACHINE\SOFTWARE\R-core\R64\3.2.1
Class Name:        <NO CLASS>
Last Write Time:   8/25/2015 - 12:08 PM
Value 0
  Name:            InstallPath
  Type:            REG_SZ
  Data:            C:\Program Files\R\R-3.2.1

Still having no luck with the install. 

Dan

**Comment by scw** [comment]
Hello Dan,

We've updated both the bridge library, and the installer. Could you update from GitHub (or download the Zip archive again) and see if the newer release fixes your issue? I'm now checking both the 32- and 64-bit registry hives, which hopefully will fix your problem. It did on the one machine I had that had a similar configuration to the one you initially posted. If it doesn't work, also let me know and we can keep digging.

Cheers,
Shaun

**Comment by dlradke** [comment]
Hey Shaun, 

The install actually worked about 2 or 3 weeks ago. Not sure why but it didn't work in the morning, and then did later that afternoon. It seems to be working well and I've been able to start developing tools using R scripts. I will run the update script just to make sure I'm up to date. Thanks for fixing the issue. 

Dan

**Comment by dlradke** [comment]
I downloaded the new release and it now gives me an error when I try and run a geoprocessing tool. 

Error in .Call("arc_warning", conditionMessage(w), PACKAGE = "rarcproxy") : 
  "arc_warning" not available for .Call() for package "rarcproxy"

I have tried to run the install bindings script and checked the override box and get this error. 

Executing: InstallBindings true
Start Time: Tue Sep 08 14:59:27 2015
Running script InstallBindings...
https://github.com/R-ArcGIS/r-bridge/releases/download/v1.0.0.113/arcgisbinding_1.0.0.113.zip
Saving URL to 'c:\users\johnra~1\appdata\local\temp\arcc016\tmpamvapm\arcgisbinding_1.0.0.113.zip'
package 'arcgisbinding' successfully unpacked and MD5 sums checked
* installing to library 'C:/Program Files/R/R-3.2.1/library'
Warning: cannot remove prior installation of package 'arcgisbinding'
R package path: C:\Program Files\R\R-3.2.1\library\arcgisbinding.
ArcGIS 10.3.1 detected. Creating link to package.
Completed script InstallBindings...
Succeeded at Tue Sep 08 14:59:29 2015 (Elapsed Time: 2.09 seconds)

Don't know what is going on but not thrilled that it is no longer working. 

Cheers,
Dan

**Comment by dlradke** [comment]
I fixed the install issue but I still get the "Error in .Call(..." when trying to run any geoprocessing tools, including the ones included in the zip file. 

Dan

**Comment by scw** [comment]
@dlradke D'oh! Sorry for introducing this issue for you. Fortunately, the fix should be easy enough. On your machine, R is installing packages into the "Program Files" directory, which requires escalated privileges to write to. We're aware of the issue and are planning a better fix, but for now, could you:
1. Close ArcMap
2. Right click on the icon you use to open it and select "Run as Administrator" and then try the upgrade script a second time.

Sorry again for the inconvenience.

**Comment by dlradke** [comment]
Okay seems to be working now. Had a bit of a scare there. 

Thanks for the help.
Dan

**Comment by scw** [comment]
Great, glad the bridge is working fine now. I think we've resolved the original registry issue with the latest release, so I'm going to mark this issue as closed, but you're welcome to create a new issue if you hit any further problems. Feel free to contact our R team if you need any assistance, we're at R_bridge@esri.com.

**Comment by josesevilla** [comment]
Hi there, 
I am now having the same error message for error in calling rarcproxy, 
I was following the instructioins in the course
