### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by alice1020** [R-ArcGIS/r-bridge-install#33]
Dear developers,
I am trying to get started with R-ArcGIS bridge, however, I am stucked int he installations process.
I have updated R to the version 3.3.1.
I have installed ArcGIS. ArcMap version 10.4.1 32-bit.
I have downloaded the zip file "r-bridge-install-master.zip".
I have unzipped the folder.
I have opened ArcMap and I have done the conncetion to the unzipped folder.
The toolbox looks empty:
![image](https://cloud.githubusercontent.com/assets/22615742/19073831/7ac9adfe-8a3d-11e6-971d-a43f8619f3e9.png)
If I open "Item Description" the wondow says: The item's XML contains errors.
What should I do?
Many thanks in advance!

Alice

**Comment by RegionHallandjsj** [comment]
Hi, I´m having the same problem. I have Arcmap 10.4.1 64-bit otherwise the same configuration as Alice. Would really appresciate some help. Thanx!
Jenny

**Comment by danistorck** [comment]
Hello, I´m having the same problem. Could you help me please! Thanks dani

**Comment by dpavlushko** [comment]
Try manual install.
1. Download [latest arcgisbinding zip package - https://github.com/R-ArcGIS/r-bridge/releases](https://github.com/R-ArcGIS/r-bridge/releases/latest)
2. Run RGui.exe and from "Menu->Packages->Install Package(s) from local files..." install R integration package.

**Comment by AnArcheo** [comment]
Hi there,
just try this[ manual instalation](https://github.com/R-ArcGIS/r-bridge-install/issues/38). 
I had also the same problem and this recipe fix my problems.
Best, 
Anna

**Comment by scw** [comment]
@alice1020 we haven't heard back from you if you've been able to resolve the issue, but there have been a few good suggestions in the comments above. I'm closing this, but if you still haven't been able to resolve the problem, feel free to reopen it.
