### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by yroell** [R-ArcGIS/r-bridge-install#34]
Hello Developers,

I am having the same issue that alice1020 is having. My screen looks the same with a red x on the R Integration toolbox. Any suggestions with how to fix this would be great.

Thanks,
Yannik

**Comment by scw** [comment]
Yannik,

In the other thread you mentioned getting past this issue. Did you take any steps beyond re-downloading the package? OK to close this issue?

Thanks,
Shaun
