### ISSUE TITLE
Error: Could not bind to a valid ArcGIS Pro installation.

### ISSUE THREAD

**Issue by Marnick** [R-ArcGIS/r-bridge-install#35]
I looked into the other issues that were raised on this error but that didn't help.
I use
- ArcGIS Pro with licences Advanced, v1.3.1.5861, valid till 31-12-2016
- R version 3.3.1 (2016-06-21) -- "Bug in Your Hair"
- R-ArcGIS bridge commit c005f4e43ffe8fc75ab82cf424e4c0c2512fe130

The toolbox was successfully installed and the check with Print R Version gave the correct result. So far so good. 
In R however I get the following result:

```
> require(arcgisbinding)
Loading required package: arcgisbinding
*** Please call arc.check_product() to  define a desktop license.
> arc.check_product()
Error: Could not bind to a valid ArcGIS Pro installation
```

Any ideas how to solve this?

**Comment by dpavlushko** [comment]
Are your using RStudio or Rgui.exe?

**Comment by Marnick** [comment]
Rstudio.
Op 19 nov. 2016 2:30 a.m. schreef Dmitry Pavlushko <notifications@github.com>:Are your using RStudio or Rgui.exe?

**Comment by dpavlushko** [comment]
Could you please try Rgui. We have a few reports when bridge failed with Rstudio but works fine with Rgui on the same machine.

**Comment by Marnick** [comment]
You are right! In Rgui it works. In Rstudio it still doesn't. This is strange. 
Op 21 nov. 2016 10:38 p.m. schreef Dmitry Pavlushko <notifications@github.com>:

**Comment by dpavlushko** [comment]
Please update `arcgisbinding` to v1.0.0.124 (https://github.com/R-ArcGIS/r-bridge/releases/latest)
