### ISSUE TITLE
Installation Problem Type 2

### ISSUE THREAD

**Issue by yroell** [R-ArcGIS/r-bridge-install#36]
Hello Developers,

I submitted an issue yesterday and today I am getting a different problem on a different computer. I have attached pictures of what issue is arising. This time, I can get within the toolbox but when I click on the Install R binding script, a red arrow is in the dialog box. The error states: " Traceback (most recent call last): File "", line 230, in updateParameters AttributeError: 'NoneType' object has no attribute 'keys' "

Any advise would be great.

Thanks,
Yannik

[rbridge_issue.docx](https://github.com/R-ArcGIS/r-bridge-install/files/545304/rbridge_issue.docx)

**Comment by scw** [comment]
Hello Yannik,

I've updated the installation so it shouldn't throw an error. Could you send on what you see if you run the "R Installation Details" script? I'm not certain, but it looks like it can't correctly determine your R installation currently.

Thanks,
Shaun
