### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by yroell** [R-ArcGIS/r-bridge-install#37]
Hey Shaun,

Attached should be a few screen shots of what is happening with the updated zip file. This is occurring on the computer that was having the traceback error. I will also try the new zip file on another computer that was having the red x issue which is a laptop. The current problem is that the dialog box is requesting a "Selected R Version" but will not allow me to input any value.

Thanks,
Yannik

[installation_error.docx](https://github.com/R-ArcGIS/r-bridge-install/files/546780/installation_error.docx)

**Comment by scw** [comment]
Hello Yannik,

I've updated the bridge to remove this validation issue. What does the "R Install Details" tool show? Basically, it looks like the installer isn't able to properly detect your R installation currently, it scans a number of registry keys to locate the R installation, it's possible these don't exist, if you send on the results of the "R Install Details" it should make that a little more clear. If you do have R installed, and it can't find it, we can work through why that might be happening.

Cheers, Shaun

**Comment by yroell** [comment]
Hey Shaun,

The new zip file worked on my laptop. I also think that I was getting
errors on one computer because it is a school computer and has weird
administrative restrictions. I will let you know if I run into any other
issues.

Thanks for all of the help,
Yannik
