### ISSUE TITLE
R Integration.pyt displays as broken (x)

### ISSUE THREAD

**Issue by HajimeSeya** [R-ArcGIS/r-bridge-install#38]
Hi, developers, 

I am. I am very sorry to bother you again by this issue.
I use ArcGIS 10.3.1 (and tried ArcGIS 4, too)  and have installed the latest version of R 3.3.2. 
The problem I am facing is that empty "R Integration.pyt," may be caused by ASCII.
It says that "ascii' codec can't decode byte 0x8e in position 10: ordinal not in range(128),"
The folder "r-bridge-install-master" is at C:\. I am very happy if you can suggest the hint to
solve this problem.

Thanks,
Hajime
![image](https://cloud.githubusercontent.com/assets/24297885/20799478/a8a63ea2-b825-11e6-818e-ce2c57149b1a.png)

**Comment by AnArcheo** [comment]
Dear Hajime,
I had the same problem, but I finally fixed it. (It worked for me perfectly)
First, You have to download latest 'arcgisbinding' package from [here: ](https://github.com/R-ArcGIS/r-bridge/releases/tag/v1.0.0.124). 
Next, install this package using R (or RStudio) from local (*zip) repository (provide path where it was downloaded). After installation You should check in R if installation was successful, typing:
> library(arcgisbinding)
*** Please call arc.check_product() to  define a desktop license.
>arc.check_product()

If there is no error messages, there is few steps to do:
1. In most cases R packages are installed in C:\Users<username>\Documents\R\win-library) so You have to copy from there 'arcgisbinding' folder and paste it into two places: 
- C:\Program Files\R\R-3.3.1 (This will require administrator privileges)
- C:\Program Files (x86)\ArcGIS\Desktop10.x\Rintegration (before that, You have to create 'Rintegration' folder in that location)

2. Next, set 'Path Environment Variable' to R and it's modules and library (like is shown [here](https://github.com/Esri/R-toolbox-py/blob/master/Doc/README.md):)
C:\Program Files\R\R-3.3.1\
C:\Program Files\R\R-3.3.1\bin
C:\Program Files\R\R-3.3.1\library
C:\Program Files\R\R-3.3.1\modules 
Remember to add a semi-colon (;) between each path!

3. Last one, download [sample-toolbox](https://github.com/R-ArcGIS/r-sample-tools) and try it :)
Good Luck!
Anna

**Comment by HajimeSeya** [comment]
It perfectly works for me!!
Thank you very much for your very detailed information, Anna.

Hajime

**Comment by AnArcheo** [comment]
I'm glad to hear!
Best work and analysis!
Anna
