### ISSUE TITLE
Manual install appears to work then running a tool it fails

### ISSUE THREAD

**Issue by nickhmorgan** [R-ArcGIS/r-bridge-install#39]
Hi 

hoping you can help 

I carried out a manual install as https://github.com/R-ArcGIS/r-bridge-install/issues/33 this all checks out as installed when running RInstall Details (see bottom). This is on server without internet access

When I try sample tools from the sample projects I get:

Running script ModelBasedClustering...
Cannot find 'rarcproxy.dll'.
Plese install Rintegration package.
Failed to execute (ModelBasedClustering).

Executing: RInstallDetails
Start Time: Wed Jan 04 17:10:16 2017
Running script RInstallDetails...
R (version 3.3.2), installed in: C:\Program Files\R\R-3.3.2
R packages will be installed into: C:\Program Files\R\R-3.3.2\library
All R package libraries detected: C:\Program Files\R\R-3.3.2\library
The ArcGIS R package (version 1.0.0.124) is installed at: C:\Program Files\R\R-3.3.2\library\arcgisbinding
Completed script RInstallDetails...
Succeeded at Wed Jan 04 17:10:16 2017 (Elapsed Time: 0.15 seconds)

**Comment by scw** [comment]
Hello @nickhmorgan,

What version of ArcGIS are you using? Could you try opening an R session, and run

```r
library(arcgisbinding)
arc.check_product()
```
Does that run correctly?

**Comment by nickhmorgan** [comment]
Thank you Shaun

That looks clear I’ll try 32 bit R

I’m using ArcGIS 10.3.1

> library(arcgisbinding)
*** Please call arc.check_product() to  define a desktop license.
> arc.check_product()
Error: Could not bind to a valid ArcGIS Pro installation.
Found ArcGIS Desktop (32-bit) Version 10.3.4959.
You'll need to use the 32-bit version of R.



Nick Morgan Senior GIS Analyst Geo Apps
Met Office  Fitzroy Road  Exeter  Devon  EX1 3PB
Tel: 44 (0)1392 886305  Fax: 44 (0)1392 885681
Email: nick.morgan@metoffice.gov.uk<mailto:tony.stevens@metoffice.gov.uk>
Web: http://www.metoffice.gov.uk<http://www.metoffice.gov.uk/>

**Comment by dpavlushko** [comment]
For ArcGIS 10.3.1 you need one extra step to complete install.
Open Command Prompt `cmd.exe` and execute following commands (change path if needed):
```
mkdir "C:\Program Files (x86)\ArcGIS\Desktop10.3\Rintegration"
mklink /J "C:\Program Files (x86)\ArcGIS\Desktop10.3\Rintegration\arcgisbinding" "C:\Program Files\R\R-3.3.2\library\arcgisbinding"
```
To validate symlink browse to `C:\Program Files (x86)\ArcGIS\Desktop10.3\Rintegration` and click on `arcgisbinding` folder, explorer should open it.

**Comment by nickhmorgan** [comment]
Thanks Shaun it ran OK in the R session but still had issues with accessing a dll when running a sample tool.

Thank you dpavlushko the mklink the sample tool worked (it did demand write access to the R library directory.
