### ISSUE TITLE
Cannot run the 'install R bindings script'

### ISSUE THREAD

**Issue by julienrenaudleca** [R-ArcGIS/r-bridge-install#4]
Hello,
using Arcgis 10.3.1
R 3.2.2

I'm having trouble running the 'Install R bindings script'. Here comes the message I get. 
Any help appreciated.
Julien

Traceback (most recent call last):
  File "<string>", line 177, in execute
  File "C:\Program Files (x86)\ArcGIS\Desktop10.3\ArcToolbox\Toolboxes\r-bridge-install-master\rtools\install_package.py", line 62, in install_package
    download_url = release_info()[0]
  File "C:\Program Files (x86)\ArcGIS\Desktop10.3\ArcToolbox\Toolboxes\r-bridge-install-master\rtools\github_release.py", line 67, in release_info
    json_r = parse_json_url(latest_url)
  File "C:\Program Files (x86)\ArcGIS\Desktop10.3\ArcToolbox\Toolboxes\r-bridge-install-master\rtools\github_release.py", line 44, in parse_json_url
    url, e))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 58: ordinal not in range(128)

Failed to execute (InstallBindings).

**Comment by scw** [comment]
Julien,

Thank you for the report. It looks like a character encoding issue, I'm guessing your locale is set to one that includes non-ASCII characters, and the code didn't anticipate that. I'm looking into the issue now.

**Comment by mhogeweg** [comment]
I got an error running the install R bindings script and was able to solve this by running ArcMap as Administrator.

**Comment by scw** [comment]
@mhogeweg the current release (2 days ago) should notify you immediately if you need to install as admin, unfortunately for 10.3.1 it needs to write to the users' Program Files directory which is protected.

**Comment by rbjork** [comment]
Same for me. So  I added Full Control privileges in the security settings for  the R folder. But my problem with import rtools persists: 'module' object has no attribute 'install_package'

After running “Install R Bindings”:

Executing: InstallBindings false
Start Time: Mon Dec 21 07:45:27 2015
Running script InstallBindings...

Traceback (most recent call last):
  File "<string>", line 164, in execute
AttributeError: 'module' object has no attribute 'install_package'

Failed to execute (InstallBindings).
Failed at Mon Dec 21 07:45:27 2015 (Elapsed Time: 0.00 seconds)



After running “Update R Bindings”:


Executing: UpdateBindings
Start Time: Mon Dec 21 07:48:37 2015
Running script UpdateBindings...

Traceback (most recent call last):
  File "<string>", line 47, in execute
AttributeError: 'module' object has no attribute 'update_package'

Failed to execute (UpdateBindings).
Failed at Mon Dec 21 07:48:37 2015 (Elapsed Time: 0.00 seconds)



After running “Print R Version”

Executing: RVersion
Start Time: Mon Dec 21 07:51:05 2015
Running script RVersion...

Traceback (most recent call last):
  File "<string>", line 74, in execute
AttributeError: 'module' object has no attribute 'r_version'

Failed to execute (RVersion).
Failed at Mon Dec 21 07:51:05 2015 (Elapsed Time: 0.00 seconds)


It seems that rtools isn’t importing fully into “R integration.pyt”
The debugging recommendation suggests checking these folders. I don’t have this and so what should I do from here?

C:\Users<username>\Documents\R\win-library) into the requested place, C:\Program Files (x86)\ArcGIS\Desktop\Rintegration

**Comment by mhogeweg** [comment]
when I ran the install 'as Administrator' it worked for me.

**Comment by scw** [comment]
@julienrenaudleca Sorry for the long delay getting back to you. I think this issue has been solved, let us know if you have any further issues using the installation.

**Comment by CodeQL** [comment]
# Hello ,mine is arcgis 10.4 ,R 3.2.5
**I received the folllowing information when I install R bindings.Hope you can help me!!

Executing: InstallBindings true
Start Time: Wed Apr 27 16:28:29 2016
Running script InstallBindings...
Saving URL to 'c:\users\duaen\appdata\local\temp\tmpmvkipw\arcgisbinding_1.0.0.118.zip'

Traceback (most recent call last):
  File "<string>", line 164, in execute
  File "E:\ESRI\R_arcgis\r-bridge-install-master\rtools\install_package.py", line 196, in install_package
    save_url(download_url, package_path)
  File "E:\ESRI\R_arcgis\r-bridge-install-master\rtools\github_release.py", line 33, in save_url
    f.write(r.read())
  File "E:\ESRI\python\ArcGIS10.4\Lib\socket.py", line 355, in read
    data = self._sock.recv(rbufsize)
  File "E:\ESRI\python\ArcGIS10.4\Lib\httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "E:\ESRI\python\ArcGIS10.4\Lib\socket.py", line 384, in read
    data = self._sock.recv(left)
  File "E:\ESRI\python\ArcGIS10.4\Lib\ssl.py", line 734, in recv
    return self.read(buflen)
  File "E:\ESRI\python\ArcGIS10.4\Lib\ssl.py", line 621, in read
    v = self._sslobj.read(len or 1024)
error: [Errno 10053] 

Failed to execute (InstallBindings).
Failed at Wed Apr 27 16:51:57 2016 (Elapsed Time: 23 minutes 27 seconds)

**Comment by scw** [comment]
Hello @CodeQL,
I've made a new release of the ArcGIS binding package which supports offline installation ([see instructions](https://github.com/R-ArcGIS/r-bridge-install/blob/master/README.md#offline-installation)). This should also serve to solve the problem you described, it looks like in your case the call to download the bridge library itself from Python is failing. This is likely to do a proxy or firewall which may restrict access to resources via Python. If you follow those instructions, and with your browser place the downloaded arcgisbinding_1.0.0.118.zip file into the same directory as the "R integration" python toolbox, the installation should proceed without needing to use Python to download the file.

Cheers, Shaun
