### ISSUE TITLE
ArcGIS Pro 1.4.1 running R scrtipt Failed

### ISSUE THREAD

**Issue by allenlu2008** [R-ArcGIS/r-bridge-install#40]
hi:
    i install R and R -bridge success.
   ArcMap running R script success.
  but ArcGIS Pro running print 
Running script Script...
*** Please install the ArcGIS R integration package
Failed to execute (Script).

and ArcGIS Pro install R-bridge success:

Running script RInstallDetails...
R (version 3.3.1), installed in: D:\Program Files\R\R-3.3.3
R packages will be installed into: D:\Program Files\R\R-3.3.3\library
All R package libraries detected: D:\Program Files\R\R-3.3.3\library;D:\Program Files\R\R-3.3.3\library
The ArcGIS R package (version 1.0.0.124) is installed at: D:\Program Files\R\R-3.3.3\library\arcgisbinding
Completed script RInstallDetails...
Succeeded at 2017年3月13日 15:33:05 (Elapsed Time: 0.08 seconds)

need you help
thank you!

**Comment by scw** [comment]
Hello @allenlu2008, thanks for the issue. Do you have background geoprocessing installed? One thing to check would be if it works from that environment, to see if the 64-bit R can talk with ArcGIS successfully in any environment. The only thing that looks strange in your R details is that your "Program Files" directory looks to be on the "D:" drive, is that correct? If it is, can you confirm you can run this from the x64 R command prompt?

```r
library(arcgisbinding)
arc.check_product()
```

If so, we can use a few alternative ways to force ArcGIS Pro to see your install, and investigate further to understand how your machine is configured to improve how the R install is detected.

Thanks,
Shaun

**Comment by allenlu2008** [comment]
my R install D: drive,running x64 R command normal
test arcgisbinding :

> library(arcgisbinding)
*** Please call arc.check_product() to  define a desktop license.
> arc.check_product()
product: ArcGIS Pro ( 11.4.0.7198 )
license: Advanced 

bug in ArcGIS Pro run r script Failed 

Thanks

allenlu2008

**Comment by scw** [comment]
@allenlu2008, 

It looks like some element of your configuration is throwing off the detection of R. In the long run, we're looking at better ways to expose configuring R from within Pro, but for the time being could you try this?

Open a command prompt, and type:

```
mkdir "C:\Program Files\ArcGIS\Pro\Rintegration"
mklink /J "C:\Program Files\ArcGIS\Pro\Rintegration\arcgisbinding" "D:\Program Files\R\R-3.3.3\library\arcgisbinding"
```
Assuming that ArcGIS Pro is installed into "C:\Program Files\ArcGIS\Pro". If it's installed elsewhere, update the paths above, and do the same steps. If it works correctly, you should be able to visit the `<ArcGIS Pro>\Rintegration` directory, and have it show the arcgisbinding package location. Pro should then work correctly.

**Comment by allenlu2008** [comment]
@scw 
I have been running these two orders, and in my pro installation directory has been a quote arcgisbinding, but still reported this error:
`
Start Time: 2017年3月15日 19:29:20
Running script Script...
*** Please install the ArcGIS R integration package
Failed to execute (Script).
Failed at 2017年3月15日 19:29:20 (Elapsed Time: 0.00 seconds)
`
Then I also tried to R / library below the arcgsibinding copy to Pro below the Rintegration directory below, and then run the script inside the R R, the results still the same failure.

**Comment by scw** [comment]
I just tried installing a copy to D:\Program Files locally, and it worked fine from Pro. Can you try reinstalling the package and see if it has any effect? You can use the tool [process monitor](https://technet.microsoft.com/en-US/sysinternals/processmonitor.aspx) to see if the DLL is being loaded correctly, but it's hard to say what the issue is without being able to reproduce it.

Let me know if that helps, Shaun

**Comment by allenlu2008** [comment]
I tried to reinstall the R and re installed the arcgisbinding package, but in the Pro is still reported the following error:
Start Time: 2017年3月17日 19:32:00
Running script Script...
*** Please install the ArcGIS R integration package
Failed to execute (Script).
Failed at 2017年3月17日 19:32:00 (Elapsed Time: 0.00 seconds)

I'm still waiting for the next version of the R language or Pro update......

Thanks again
