### ISSUE TITLE
Problem Installing ArcGIS Bindings v 1.0.0.124

### ISSUE THREAD

**Issue by andytrcka** [R-ArcGIS/r-bridge-install#41]
I am encountering the following error in ArcCatalog when attempting to Install R Bindings:

_Executing: InstallBindings true 3.3.3
Start Time: Mon Mar 13 13:01:10 2017
Running script InstallBindings...

Traceback (most recent call last):
  File "<string>", line 248, in execute
  File "C:\Program Files (x86)\ArcGIS\Desktop10.3\Rintegration\r-bridge-install-master\r-bridge-install-master\rtools\install_package.py", line 150, in install_package
    (install_dir, arc_version, product) = arcgis_platform()
  File "C:\Program Files (x86)\ArcGIS\Desktop10.3\Rintegration\r-bridge-install-master\r-bridge-install-master\rtools\install_package.py", line 69, in arcgis_platform
    info = arcpy.GetInstallInfo()
AttributeError: 'module' object has no attribute 'GetInstallInfo'

Failed to execute (InstallBindings).
Failed at Mon Mar 13 13:01:10 2017 (Elapsed Time: 0.01 seconds)_

Background Info:
- I have tried installing KB2533623 on Windows 7, but am told the patch does not apply to my system
- I successfully installed R "Installed package(s) from local files." The local files were saved to this location: 	C:\Program Files (x86)\ArcGIS\Desktop10.x\Rintegration     
- After running arc.check_product in R.386.3.3.3 the following info was returned: product = ArcGIS Desktop (10.3.1.4559), License = Advanced
- I have tried the offline installation of R and R Bindings
- I have tried saving to and running Install R Bindings in ArcCatalog from the following locations and receive the error above for BOTH locations: •	C:\Program Files\R\R-3.3.1   •	C:\Program Files (x86)\ArcGIS\Desktop10.x\Rintegration 
- I am an administrator on my machine and I logged in as an administrator. I also ran ArcCatalog as an administrator and have been greeted with the error above for both

Thank you and Please Help!!!!

**Comment by andytrcka** [comment]
Forgot to mention... I also configured the Path environmental variable to accommodate R. But I am curious if I entered the path info info correctly as I entered these four into path (each separated by a semi-colon):
C:\Program Files\R\R-3.3.1
C:\Program Files\R\R-3.3.1\bin
C:\Program Files\R\R-3.3.1\library
C:\Program Files\R\R-3.3.1\modules

**Comment by scw** [comment]
Hello @andytrcka, I see you closed this issue &mdash; did you already resolve it yourself? If not, happy to help look into the issue for you. Nothing you did looks incorrect, though I can't see why ArcPy is unable to run the `GetInstallInfo()` function. If you are still having problems, could you try typing the following into the Python window of ArcMap?
```python
arcpy.GetInstallInfo()
```

**Comment by andytrcka** [comment]
Shaun,

Thanks for getting ahold of me. I mistakenly closed this issue! IT should
still be open. At work tomorrow I'll try what you suggested and let you
know the results.

Again...

Thanks!!

-a.t.

**Comment by andytrcka** [comment]
I ran arcpy.GetInstallInfo as instructed:
>>> arcpy.GetInstallInfo()
{'SourceDir': u'C:\\Windows\\ccmcache\\c7\\Client\\SetupFiles\\', 'InstallDate': u'4/8/2016', 'InstallDir': u'c:\\program files (x86)\\arcgis\\desktop10.3\\', 'ProductName': u'Desktop', 'BuildNumber': u'4959', 'InstallType': u'N/A', 'Version': u'10.3.1', 'SPNumber': u'N/A', 'Installer': u'SYSTEM', 'SPBuild': u'N/A', 'InstallTime': u'14:25:25'}
>>>

**Comment by scw** [comment]
Hi @andytrcka OK, that looks fine. Not sure what's up with ArcCatalog, but rereading your initial issue, it sounds like it's installed OK &ndash; if you see the message

```
product: ArcGIS Desktop (10.3.1.4559)
License: Advanced
```

That means you're all set! The bridge is installed, and can be used from within R. If you'd like to use it from within ArcGIS, you can try one of the sample tools from the [sample tools](https://github.com/R-ArcGIS/r-sample-tools) repository, or can use the self-tests provided within the package. Those are included in a toolbox located in `C:\Program Files\R\R-3.3.1\library\arcgisbinding\examples`, add that location to ArcMap or ArcCatalog, and try running any of the tools. If they produce output, you're in business.

Cheers,
Shaun
