### ISSUE TITLE
Link to "sample tools" is broken in README.md

### ISSUE THREAD

**Issue by EdFarrell** [R-ArcGIS/r-bridge-install#42]
In the ###ArcGIS Pro 1.1+ section in the main README.md, the "sample tools" link gives a 404. https://github.com/R-ArcGIS/r-bridge/tree/master/package/arc/inst/examples

**Comment by scw** [comment]
@EdFarrell thanks for the report! I've updated the links to point at the correct location for the included samples.

Cheers, Shaun
