### ISSUE TITLE
Error in .Call("arc_error", msg, PACKAGE = "rarcproxy")  after Offline installation

### ISSUE THREAD

**Issue by hlzhang525** [R-ArcGIS/r-bridge-install#43]
Hi, guys,

We need your investigation and assistance ...

Firstly, without firewall, all with R-ArcGIS Bridge 1.0.0.124, including installation and running R models within ArcGIS, are fine. Excellent effort ....

Secondly, with "offline" installation of R-ArcGIS Bridge behind the firewall, the process looks fine (not completely sure).

We got: Error in .Call("arc_error", msg, PACKAGE = "rarcproxy"), once Run the sample 'Model Based Cluster' and other models in ArcGIS.

The details are as follows:

Part 1:  Offline Install R bindings:

Executing: InstallBindings true 3.2.5
Start Time: Sun Apr 16 07:49:09 2017
Running script InstallBindings...
Unable to access'https://api.github.com/repos/R-ArcGIS/r-bridge/releases/latest', error: UnauthorizedBrowser.
Unable to get current release information. Trying offline installation.
Found local copy of binding, installing from zip
Rcmd.exe INSTALL d:\users\...\appdata\local\temp\tmp4svrl2\arcgisbinding_1.0.0.124.zip
'C:\Program' is not recognized as an internal or external command,
**R command returned non-zero exit status.**
Rscript.exe d:\users\...\appdata\local\temp\tmp4svrl2\install.R
package 'arcgisbinding' successfully unpacked and MD5 sums checked
Installing package into 'D:/Users/.../Documents/R/win-library/3.2'
(as 'lib' is unspecified)
Completed script InstallBindings...
Succeeded at Sun Apr 16 07:49:18 2017 (Elapsed Time: 9.79 seconds)

Part 2: After RUN the sample 'Model Based Cluster' on the above installation:

Executing: ModelBasedClustering spruce_trees D:\Users\...\Documents\ArcGIS\Default.gdb\spruce_trees_ModelBasedClust # # #
Start Time: Sun Apr 16 07:50:29 2017
Running script ModelBasedClustering...
**Error in .Call("arc_error", msg, PACKAGE = "rarcproxy") : 
  "arc_error" not available for .Call() for package "rarcproxy"**
Completed script ModelBasedClustering...
Succeeded at Sun Apr 16 07:50:31 2017 (Elapsed Time: 1.43 seconds)

**Comment by andyfarmerboy** [comment]
As I mentioned in the other thread I am experiencing a very similar error attempting to run R scripts in ArcGIS Pro 2.1.1.  I was able to install the bindings manually but all scrips return the following error.
![untitled-2](https://user-images.githubusercontent.com/14131345/36346485-843e5938-140d-11e8-910f-e931232335a5.png)
Any assistance is appreciated.  Thanks!

**Comment by andyfarmerboy** [comment]
I installed a new version of R and this issue seems to be resolved.  Thanks.

**Comment by scw** [comment]
@andyfarmerboy Cool, thanks for letting us know. I'll close this issue, we can reopen it if further similar problems occur.
