### ISSUE TITLE
still asked to "install ArcGIS R integration package"

### ISSUE THREAD

**Issue by steveeyre** [R-ArcGIS/r-bridge-install#45]
I've installed the lasted version of R-bridge, and then, when trying to execute the toolbox, ArcGIS still displays a error: "Please install ArcGIS R integration package."

![20170508135149](https://cloud.githubusercontent.com/assets/8066339/25817568/c4fff83a-33f5-11e7-8049-c7bca11cb947.png)

**Comment by scw** [comment]
Hello @steveeyre,

Does it work from within an R session? What versions of ArcGIS and R are you using?

Thanks,
Shaun

**Comment by steveeyre** [comment]
@scw Hi, thank you for reply. Which file should I try to execute in the R session, is it the .pyt one? 
I'm using R 3.3.1, and ArcGIS 10.4.1.

**Comment by scw** [comment]
@steveeyre,

To see if the bridge is installed correctly from R, you can open an R window, and type:

```r
library(arcgisbinding)
arc.check_product()
```
If the package is correctly installed, that should provide some details about the ArcGIS environment that it was able to detect. If it doesn't, let us know what it says.

Also, from the toolbox, could you paste the results of running the "R Installation Details" tool? It should provide some context to what it sees in your R installation.

Thanks,
Shaun

Thanks,
Shaun

**Comment by steveeyre** [comment]
@scw Thank you, the problem has been solved. 
I check it in the R window and it said "Error: Could not bind to a valid ArcGIS Pro installation. Found ArcGIS Desktop (32-bit) Version 10.4.5686. You'll need to use the 32-bit version of R."

(but I am pretty sure the R is 32/64-bit compatible)

I re-download a R 3.4.0 32/64-bit and try to execute the toolbox again, and now it works. The "R Installation Details" window has always been empty. And after the re-download, the arc.check_product() check still displays the same error.

**Comment by scw** [comment]
Hi @steveeyre,

Glad you were able to resolve your issue. You're right that R includes both 32- and 64-bit versions (labeled i386 and x64 respectively). However, ArcGIS Desktop is a 32-bit application, so you'll need to use the 32-bit version of R when working with it. Pro is 64-bit, and instead works with the 64-bit version of R, as shown in this diagram:
  https://raw.githubusercontent.com/R-ArcGIS/r-bridge-install/master/img/version-block-detailed.png

Let us know if you have any further issues working with the bridge, for now I'll close this issue as it sounds like you're up and running.

Cheers, Shaun
