### ISSUE TITLE
Problem installing the toolbox

### ISSUE THREAD

**Issue by camarimar** [R-ArcGIS/r-bridge-install#48]
Hello!

I am trying to install the R-ARCGIS toolbox but this message appears everytime I click on the install button:

Link failed.
Completed script InstallBindings...
Failed to execute (InstallBindings).
Failed at Mon Jun 19 14:37:07 2017 (Elapsed Time: 2.33 seconds)

Thank you for your help.

**Comment by scw** [comment]
Hello @camarimar,

It looks like you're installing into ArcMap 10.3.1, is that right? Do you get any messages prior to "Link failed"? For 10.3.1, you'll need to first start ArcMap as administrator:

> Start ArcMap as an administrator, by right clicking the icon, selecting 'Run as Administrator', then trying the script

**Comment by camarimar** [comment]
Thank you for your reply @scw. I tried it starting the program as an administrator but I got the same result. The messages that are generated by trying the script are:

Unable to locate the requested R command: C:\Program FIles\R\R-3.3.3\bin\i386\Rcmd.exe
Unable to locate the requested R command: C:\Program FIles\R\R-3.3.3\bin\i386\Rcmd.exe
Fallback installation method failed.
Unable to locate R package library. Link failed. 
Completed script InstallBindings
Failed to execute (InstallBindings)

**Comment by scw** [comment]
Hello @camarimar,

Can you confirm that the executable exists at that location? It's possible that the installer detected an invalid installation of R which is still included in the registry. If that's the case, can you confirm what versions of R are present in C:\Program Files\R? It's possible that you have R installed, but only the x64 (64-bit) version.

**Comment by scw** [comment]
Hello @camarimar,

It sounds like you don't have the 32-bit version of R installed. Try reinstalling R, and make sure the 32-bit files are also installed:

<img width="498" alt="install-32-bit-components" src="https://user-images.githubusercontent.com/1314/27650875-5fcc478e-5c04-11e7-91a6-82112b5be078.png">

If you only want to use 64-bit R, you can install Background Geoprocessing to work with the bridge, or you can use ArcGIS Pro.

Cheers,
Shaun

**Comment by scw** [comment]
@camarimar I'm going to close this issue, and hoping that adding the 32-bit components solved your issue. If it didn't, feel free to reopen the issue and we can look into it further.
