### ISSUE TITLE
Problem installing the toolbox (version Pro 1.4)

### ISSUE THREAD

**Issue by aicelm** [R-ArcGIS/r-bridge-install#50]
Hi! I have a problem installing R-ArcGIS Toolbox, 

I've downloaded this repo, then I 've created a new Toolbox adding the folder "R Integration.pyt" and only I view a script call it "Tool" that it runs ok, but it doesn't show anything. 

This is the screen capture:
![image](https://user-images.githubusercontent.com/25487196/27349710-7484037c-55f8-11e7-8e7a-0a94e1287d56.png)

I don't know where are the others files, 

Thank you for all
Regards

**Comment by scw** [comment]
Hello @aicelm,

Can you add a folder connection to the location where you downloaded the repository? You shouldn't need to make any new toolboxes, but use the one that's included here by opening it. Here's a short video of the steps to add the toolbox:

![r-bridge-install-add-toolbox](https://user-images.githubusercontent.com/1314/27350947-d71057ea-55c9-11e7-8dd6-3db2593a2d6e.gif)

Can you try that approach and let us know if it works for you?

Thanks,
Shaun

**Comment by aicelm** [comment]
Hi! 

I've pull down the repository again and I've followed the same steps.
I already have the good folder.

Thank you so much!
Leticia

**Comment by scw** [comment]
Great! Let us know if you have any other questions or issues.

Cheers, Shaun
