### ISSUE TITLE
R Integration.pyt displays as broken (x)

### ISSUE THREAD

**Issue by dayttt** [R-ArcGIS/r-bridge-install#53]
hi guys, 

i have the same problem with #14 and #44 . arcgis 10.5 and win 10 64 bit. i already setup r.  python and arcgis same drive.(c:) 

this is my problem. do you know any solution? 

![2017-10-02_22-33-01](https://user-images.githubusercontent.com/32465859/31095639-334438c0-a7c2-11e7-83c4-3bfab15e6da1.png)

**Comment by scw** [comment]
@dayttt I've uploaded a new build -- can you try it on your end and see if it resolves your issue?

Thanks, Shaun

**Comment by dayttt** [comment]
thank you for your interest. but unfortunately it seems doesn't work. i have error this 

![2017-10-03_22-02-22](https://user-images.githubusercontent.com/32465859/31143752-f545cec4-a886-11e7-9d65-6980967dffc7.png)

**Comment by scw** [comment]
OK, looks like a Python 2 specific issue -- could you try downloading again and rerunning? Thanks for your patience.

**Comment by dayttt** [comment]
there is still same problem go on. :( 
i thank you for your effort. 

![2017-10-03_23-32-58](https://user-images.githubusercontent.com/32465859/31147668-42105eb6-a893-11e7-8d31-180e2932e2c2.png)

**Comment by scw** [comment]
OK, I'll stand up a machine using cp1254 as its default encoding and try to reproduce the issue.

**Comment by scw** [comment]
Great! Glad you're up and running. Let us know if you have any other questions or issues.

Cheers, Shaun
