### ISSUE TITLE
Cannot install to default package directory

### ISSUE THREAD

**Issue by kkkemp** [R-ArcGIS/r-bridge-install#57]
I use ArcGIS Pro on a  VM.  R was installed by our admin in a drive in which I cannot write. So when I try to run the install package in ArcGIS Pro it fails because it is trying to write to C: drive. I tried using the manual install in R, but it still tried to install in the default directory. I have tried to install using install.packages() command in R but I'm not sure I've set all the options correctly. Besides it seems that the zip file that I get from the github download is not the one that install.packages is looking for. How to proceed?

**Comment by dpavlushko** [comment]
Download latest [arcgisbinding](https://github.com/R-ArcGIS/r-bridge/releases/tag/v1.0.0.128) zip and install it in RGui
![image](https://user-images.githubusercontent.com/12039804/32590269-69aa7b44-c4ce-11e7-9f69-bac5f08eaa78.png)

**Comment by kkkemp** [comment]
Thanks, got it.

**Comment by scw** [comment]
@kkkemp it looks like you were able to resolve this issue -- I'll close it for now, but if you hit any snags, feel free to reopen it and we can dig into it further.
