### ISSUE TITLE
RInstallDetails returns incorrect info

### ISSUE THREAD

**Issue by wadloopoer** [R-ArcGIS/r-bridge-install#59]
After a successful install, arcgisbinding works fine, but RInstallDetails indicated that "The ArcGIS R package is not installed" (see below)

I suspect this is because because my /Documents folder is located on a different drive (D:).  InstallBindings appears to have gleaned this, but RInstallDetails did not.  I have confirmed that the /arcgisbinding is located on my D: drive

Executing: InstallBindings true 3.4.2
Start Time: Mon Dec 18 17:35:35 2017
Running script InstallBindings...
Saving URL to 'c:\users\[user]\appdata\local\temp\tmpxfdjkv\arcgisbinding_1.0.0.128.zip'
Rcmd.exe INSTALL c:\users\[user]\appdata\local\temp\tmpxfdjkv\arcgisbinding_1.0.0.128.zip
package 'arcgisbinding' successfully unpacked and MD5 sums checked
* installing to library 'D:/Users/[user]/Documents/R/win-library/3.4'
Completed script InstallBindings...
Succeeded at Mon Dec 18 17:35:43 2017 (Elapsed Time: 7.23 seconds)

Executing: RInstallDetails
Start Time: Mon Dec 18 17:36:11 2017
Running script RInstallDetails...
R (version 3.4.2), installed in: C:\Program Files\R\R-3.4.2
R packages will be installed into: C:\Users\[user]\Documents\R\win-library\3.4
All R package libraries detected: C:\Users\[user]\Documents\R\win-library\3.4;C:\Program Files\R\R-3.4.2\library
The ArcGIS R package is not installed. Use the 'Install R Bindings' tool to install it.
Completed script RInstallDetails...
Succeeded at Mon Dec 18 17:36:11 2017 (Elapsed Time: 0.05 seconds)

**Comment by scw** [comment]
@wadloopoer I've pushed a commit which should resolve this issue. Could you confirm on your end?

Thanks, Shaun

**Comment by wadloopoer** [comment]
@scw - confirmed, thanks

Executing: RInstallDetails
Start Time: Mon Jan 08 14:44:13 2018
Running script RInstallDetails...
R (version 3.4.2), installed in: C:\Program Files\R\R-3.4.2
R packages will be installed into: D:\Users\[user]\Documents\R\win-library\3.4
All R package libraries detected: D:\Users\[user]\Documents\R\win-library\3.4;C:\Program Files\R\R-3.4.2\library
The ArcGIS R package (version 1.0.0.128) is installed at: D:\Users\[user]\Documents\R\win-library\3.4\arcgisbinding
Completed script RInstallDetails...
Succeeded at Mon Jan 08 14:44:13 2018 (Elapsed Time: 0.06 seconds)

**Comment by scw** [comment]
@wadloopoer great, thanks! I'll close this for now.
