### ISSUE TITLE
R Integration Toolbox not opening. Red cross  "X" on  icone instead

### ISSUE THREAD

**Issue by mlineF** [R-ArcGIS/r-bridge-install#61]
Hi,

I've just downloaded the folder and I failed to open the toolbox "R Integration.pyt" in Catalogue.
The icon looks like on the picture below:
![image](https://user-images.githubusercontent.com/35834275/35432850-aed68ca8-0281-11e8-9eaf-407919ae3496.png)

It seems that an error is occurring with the Python script. I have a ArcGis 10.3 version and R 3.4 version. 
That's what I get when I check the synthax : 

![image](https://user-images.githubusercontent.com/35834275/35433131-9545cdc0-0282-11e8-9be3-ef4c5e840761.png)

Thank you for your help.

**Comment by mlineF** [comment]
Hi Shaun, 

Thank you for your help. But I still get a red cross on the the toolbox "R Integration.pyt". 

![image](https://user-images.githubusercontent.com/35834275/36310646-01ff993a-1329-11e8-9de6-7b5cf92c7856.png)

**Comment by scw** [comment]
OK, could you try pulling one more time?

**Comment by mlineF** [comment]
It looks like it's working I can see and launch the Install R bindings tool. 
Awesome Shaun !
Thanks a lot

**Comment by scw** [comment]
@mlineF Great! Let us know if you have any other questions or issues.

Cheers, Shaun
