### ISSUE TITLE
issue in installing r-bridge-install

### ISSUE THREAD

**Issue by hongfzh** [R-ArcGIS/r-bridge-install#62]
ArcGIS 10.5 and R-3.4.3, but the r-bridge-install cannot be installed. the page I getted:
![1](https://user-images.githubusercontent.com/36200397/35869152-60e48d58-0b99-11e8-993c-17c1a31eb3c8.png)
![2](https://user-images.githubusercontent.com/36200397/35869154-617c40b2-0b99-11e8-9ae9-51802d49a70c.png)

**Comment by scw** [comment]
Hello @hongfzh, could you copy and paste the full text from the error message? Thanks!

**Comment by hongfzh** [comment]
Hello @scw, the full textr of the error message is 
"Executing: InstallBindings true 3.4.3
Start Time: Wed Feb 07 09:55:55 2018
Running script InstallBindings...
Updating default R to 3.4.3
Saving URL to 'c:\users\hfz\appdata\local\temp\tmpftr7xf\arcgisbinding_1.0.0.128.zip'
Unable to locate requested R command: D:\Program Files (x86)\R\R-3.4.3\bin\i386\Rcmd.exe
Unable to locate requested R command: D:\Program Files (x86)\R\R-3.4.3\bin\i386\Rscript.exe
Fallback installation method failed.
Completed script InstallBindings...
Failed to execute (InstallBindings).
Failed at Wed Feb 07 09:56:31 2018 (Elapsed Time: 35.60 seconds)"
Thanks!

**Comment by hongfzh** [comment]
Hello @swc, I reinstalled R software, and the "r-bridge-install" installed successfully. Thank you for the reminder!

**Comment by scw** [comment]
Great! Let us know if you have any further issues.
