### ISSUE TITLE
How to install R-Bridge on ArcGIS for Servers 10.5? (Help Wanted)

### ISSUE THREAD

**Issue by wondie** [R-ArcGIS/r-bridge-install#63]
I wanted to use this tool because R console couldn't run when called from Python Geoprocessing tool.

**Comment by dpavlushko** [comment]
1. download latest arcgsbinding package from this location [https://github.com/R-ArcGIS/r-bridge/releases/latest](https://github.com/R-ArcGIS/r-bridge/releases/latest)
2. Run RGui, click on application menu Packages->Install package(s) from local zip files...
![image](https://user-images.githubusercontent.com/12039804/36178881-39dd48e0-10cf-11e8-9357-300a6751c39c.png)
pick `arcgisbinding_1,0,0.128.zip` and install the package.
3. Open user AppData folder, usually `C:\Users\<USERNAME>\AppData\Local\ESRI`. Create 'RIntergation.conf' file and and add one line: R_HOME=C:\Program Files\R\R-3.3.2 (adjust path if needed)
or execute this command line:
```bat
C:\> echo R_HOME=C:\Program Files\R\R-3.3.2 > %APPDATA%\..\Local\Esri\RIntergation.conf
```

**Comment by wondie** [comment]
Thank you very much for the help. Unfortunately, I couldn't run r scripts from my Python toolbox. I was using python subprocess.call() method to call some CMD commands calling and using r scripts. Is there a way of making this work? It works well in ArcGIS Desktop.

**Comment by scw** [comment]
@wondie Could you share some details on how you're trying to execute R with the package? The two main deployment stories are:

1. Create an R script which takes inputs and outputs like any other Geoprocessing tool, and reference it within a toolbox.
2. Create R scripts which don't use the Geoprocessing framework, but include their inputs explicitly, and write the data back via the package.

Can you use either of these above patterns? If you do need to use subprocess calls, can you provide some details about what you're trying to do? If you just need to call R from Python, you should be able to make an R script tool, then execute it from Python by importing the toolbox and calling the tool as you would with any Python tool or ModelBuilder model. If you have other reasons to need subprocess calls, share a little more about what you're doing and we can take a look.

**Comment by wondie** [comment]
@scw what I am using is similar to the first option. I am happy to change subprocess.call() if there is a working alternative. 
This is how it is used in the toolbox. 
 ```

 r_cmd = '"' + r_exe_path + '" --vanilla --slave --file="' + ras_temp_path + 'out_script.r"'  # r command

        arcpy.AddMessage("Running similarity analysis \n")
        # TODO Apply this change on desktop version
        CREATE_NO_WINDOW = 0x08000000
        # Open shell and run R command
        subprocess.call(shlex.split(r_cmd), shell=False, creationflags=CREATE_NO_WINDOW)
```
The out_script.r
contains the following command. 

```
source("D:/mytool/R_Scripts/similarity_analysis.r"); 
similarityAnalysis(1,"D:/mytool/R_Scripts/readAscii.r","D:/mytool/R_Scripts/writeAscii.r","C:/Users/User/Documents/ArcGIS/scratch/Temp/") 
```
The use of the R scripts is to create ASCII files for statistics Mahalanobis and Multivariate Environmental Similarity Surfaces (MESS). 

The above approach works in Desktop but not in the server.

**Comment by wondie** [comment]
Is there anything wrong with my implementation?

**Comment by wondie** [comment]
@scw thank you!

**Comment by wondie** [comment]
Could incompatibility of Python 64 bit (For server) and 32 bit for R be the cause of the problem?

**Comment by MichaelGGeoda** [comment]
Can anyone please comment on ArcGIS Server unable to locate R-Brigde? I have both desktop and server on the same machine. I can run R in desktop but publishing it as a GP service always bring "R Bridge not installed" from the AGS service log.
Thanks!

**Comment by scdub** [comment]
@MichaelGGeoda Do you run Server as a different user than your personal user account? You will need to have a `Rintergation.conf` file in `%LOCALAPPDATA%\ESRI` for the Server user as well for it to find R, with the value of R_HOME set as @dpavlushko described above.

**Comment by orhuna** [comment]
@MichaelGGeoda, it is also worth taking a look at the [enterprise documentation for arcgisbinding](https://enterprise.arcgis.com/en/server/10.6/publish-services/linux/deploying-r-for-arcgis-server.htm)

**Comment by scdub** [comment]
Closing this issue, the above documentation can be referenced for future folks trying to install on Server.
