### ISSUE TITLE
arc.open error Error in (function (cl, name, valueClass)

### ISSUE THREAD

**Issue by rmdewan** [R-ArcGIS/r-bridge-install#66]
My R code looks like:
vac <- arc.open("completepath/filename.gdb")
and I am getting the following error:

Error in (function (cl, name, valueClass)  : 
  assignment of an object of class “numeric” is not valid for @‘.ptr’ in an object of class “arc.workspace_impl”; is(value, "externalptr") is not TRUE

**Comment by scw** [comment]
@rmdewan the bridge doesn't directly handle workspaces (like a GDB), you'll need to pass in a fully qualified path to a specific datasource (like a feature class residing in the GDB).

**Comment by rmdewan** [comment]
Thanks Shaun,
Rajiv

--
Rajiv Dewan
Xerox Professor of Business
Computers & Information Systems and Business Analytics
Simon School, University of Rochester
3-333B Carol Simon Hall
Rajiv.dewan@simon.rochester.edu<mailto:Rajiv.dewan@simon.rochester.edu>    585 275 3827

**Comment by scw** [comment]
@rmdewan No problem, happy to help. I'll make a note that we should provide a more useful error message if you pass in a workspace to `arc.open`.

**Comment by rmdewan** [comment]
Hi Shaun,
  I am very familiar with R but a complete novice with ArcGIS.  Some one sent me this GDB file which I can open in ArgGIS Pro.  It is folder with very many files in it of the following kinds: ATX, GDBTABLE, GDBINDEXES, and SPX among a couple of others.  I want to extract the lat/log into an R dataset.  Which of these should I try to open in arc.open()?

Thanks and sorry for the very newbie question,
Rajiv

--
Rajiv Dewan
Xerox Professor of Business
Computers & Information Systems and Business Analytics
Simon School, University of Rochester
3-333B Carol Simon Hall
Rajiv.dewan@simon.rochester.edu<mailto:Rajiv.dewan@simon.rochester.edu>    585 275 3827

**Comment by dpavlushko** [comment]
Try beta release [1.0.1.229-beta](https://github.com/R-ArcGIS/r-bridge/releases/tag/v1.0.1.229-beta) it should be more friendly with opening .gdb workspace.

**Comment by rmdewan** [comment]
Thanks a lot,
Rajiv
--
Rajiv Dewan
Xerox Professor of Business
Computers & Information Systems and Business Analytics
Simon Business School, University of Rochester
Carol Simon Hall Room 3-333B
585 275 3827























On Feb 23, 2018, at 5:52 PM, Dmitry Pavlushko <notifications@github.com<mailto:notifications@github.com>> wrote:


Try beta release 1.0.1.229-beta<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_R-2DArcGIS_r-2Dbridge_releases_tag_v1.0.1.229-2Dbeta&d=DwMCaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=8A2X9fsVWLhm3sS-7EDsm2-rfODDIKyWrMN4QLOm7cs&m=ewQN8MHkwc1l2tOKh0sc8p8xmUyQGTK3CepMY1Pxqw8&s=7dKwLCYNgS0UEJRcaL-7P2Q8Q1vGiU18qD-euarBXb0&e=> it should be more friendly with opening .gdb workspace.

**Comment by scw** [comment]
Hi @rmdewan, no problem. File Geodatabases are a collection of files comprising the database. This database can contain many different data sets all within it, but unfortunately as a pure database, you can't immediately tell from the filenames on disk what it contains. If you can open the data in ArcGIS Pro, you should be able to navigate to the GDB, and see the feature class, raster or table names from within the application.  Once you see one of those names, you can add it after ".gdb/" and it'll be openable within R.

**Comment by rmdewan** [comment]
That is a cool tip Shaun.
Thanks
Rajiv
--
Rajiv Dewan
Xerox Professor of Business
Computers & Information Systems and Business Analytics
Simon Business School, University of Rochester
Carol Simon Hall Room 3-333B
585 275 3827























On Feb 23, 2018, at 6:26 PM, Shaun Walbridge <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @rmdewan<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_rmdewan&d=DwMFaQ&c=kbmfwr1Yojg42sGEpaQh5ofMHBeTl9EI2eaqQZhHbOU&r=8A2X9fsVWLhm3sS-7EDsm2-rfODDIKyWrMN4QLOm7cs&m=116XU_mj9E8mg08IkkuqfdRldTO_HhSlFEFMVohrylo&s=T2YqrzxlnISGzBZVTQ6nuuaJmT3E3T_OF0F6C3RHj50&e=>, no problem. File Geodatabases are a collection of files comprising the database. This database can contain many different data sets all within it, but unfortunately as a pure database, you can't immediately tell from the filenames on disk what it contains. If you can open the data in ArcGIS Pro, you should be able to navigate to the GDB, and see the feature class, raster or table names from within the application. Once you see one of those names, you can add it after ".gdb/" and it'll be openable within R.
