### ISSUE TITLE
ArcGIS Pro 2.1 installation problem

### ISSUE THREAD

**Issue by yunusserhat** [R-ArcGIS/r-bridge-install#67]
Hi Shaun, 

I have some problem with ArcGIS Pro 2.1. This is my problem;
![screenshot_1](https://user-images.githubusercontent.com/35924790/38646475-cf58491c-3df0-11e8-975b-66a44577480b.png)

Not show installation tab.

**Comment by yunusserhat** [comment]
Ok, I started with Admin authorization and solved. Thanks.

**Comment by scw** [comment]
@yunusserhat Cool, glad you were able to resolve this. Also note that with ArcGIS Pro, the installer is built right into the application now:

![r in arcgis pro](https://user-images.githubusercontent.com/1314/38690132-575ad884-3e4b-11e8-8f67-298c5f251172.gif)

**Comment by yunusserhat** [comment]
this is very good news. thanks
