### ISSUE TITLE
'Install R bindings' problem with R 3.4.3 and Pro 2.1.3

### ISSUE THREAD

**Issue by jbeaulie** [R-ArcGIS/r-bridge-install#69]
When running the 'Install R bindings' tool from ArcGIS Pro, I get the following error message:

![image](https://user-images.githubusercontent.com/6340340/41481152-e7d290de-709e-11e8-93ad-3b3de9599e53.png)

**Comment by orhuna** [comment]
Hello @jbeaulie . Can you please try these steps?
1. Open R Studio (or any IDE you use)
2. Run ``` trace(utils:::unpackPkgZip, edit=TRUE)```
3. Launch Pro
4. Click **Project** Ribbon
5. Click **Options**
6. Click on **Geoprocessing** tab
7. Under R-ArcGIS Support Click on this box 
![image](https://user-images.githubusercontent.com/5066435/42954480-b475e792-8b31-11e8-95ff-e9606c3bd0d4.png)
8. Select Download Latest Version

Make sure the Detected R home directory is pointing to the version of R you used in step 2 (that is in case you have multiple versions of R installed).

**Comment by scw** [comment]
@jbeaulie Hello Jake, were you able to install the bindings package either on your own or following Orhun's instructions?

**Comment by ratnanil** [comment]
I had a similar issue using R version 3.5.1 (2018-07-02) on x86_64-w64-mingw32 with ArcGIS Pro 2.2.0. I was able to install the bridge with @orhuna's instuctions. Since `Sys.sleep` was not available I skipped steps 1 - 3, downloaded the latest version and installed via the option "install from file".

Here's the (german) error message that I recieved before finding this workaround.

```
Warnung in install.packages("C:/Users/rata/AppData/Local/Temp/ArcGISPro7784/tmpklj6a_67/arcgisbinding_1.0.1.232.zip",
 'lib = "C:/Program Files/R/R-3.5.1/library" ist nicht schreibbar
 Fehler in install.packages("C:/Users/rata/AppData/Local/Temp/ArcGISPro7784/tmpklj6a_67/arcgisbinding_1.0.1.232.zip",  :
 kann keine Pakete installieren
 Ausführung angehalten
 R command returned non-zero exit status.
 Fallback installation method failed.
```

**Comment by ratnanil** [comment]
Here's a nice tutorial on these steps https://youtu.be/lEKx_pJIKj0?t=773
