### ISSUE TITLE
Install.Packages

### ISSUE THREAD

**Issue by bgalvezs** [R-ArcGIS/r-bridge-install#70]
Hi Support.
I need your help, because I have an error with the install of R-Bridge (I´m attaching)

![image](https://user-images.githubusercontent.com/13021944/43407465-d7ab1430-93ec-11e8-8715-7b3774cb6e28.png)
![r-support](https://user-images.githubusercontent.com/13021944/43407528-fff60062-93ec-11e8-9261-19f89ca9a233.png)

Can you help me please?

I hope your comments.

Braulio.

**Comment by dpavlushko** [comment]
Please try to install the bridge package from R. 
a. Download latest zip package from https://github.com/R-ArcGIS/r-bridge/releases/latest
b. Browse to R installation folder, run RGui.exe then Menu->Packages->Install package(s) from  local files..., navigate to download folder and pick arcgisbinding_1.0.1.232.zip.

If you have a problem with RGui.exe re-install R.

**Comment by scw** [comment]
Hello @bgalvezs, have you been able to resolve this issue with the steps Dima outlined above?

**Comment by bgalvezs** [comment]
Hi scw.
I still don't do this suggestion because we are resolving others issues in ArcGIS Pro.
ASAP I have news about this. Thanks!
