### ISSUE TITLE
Error: Failed to initialize R interpreter #73

### ISSUE THREAD

**Issue by imagesbyjohnyoung** [R-ArcGIS/r-bridge-install#74]
https://github.com/R-ArcGIS/r-bridge-install/issues/73#issuecomment-413366464

Not sure why issued closed?

No solution to this as yet

**Comment by scw** [comment]
Hi @imagesbyjohnyoung, GitHub reports that you closed the issue on the 15th -- I've reopened it, and will close this one. Cheers, Shaun
