### ISSUE TITLE
R-Bridge in a multi-user environment

### ISSUE THREAD

**Issue by albur2018** [R-ArcGIS/r-bridge-install#76]
We have no problems to install and use R-bridge as administrator. But if a standard user tries to use it an error message appears that there are no edit rights for the library folder of R in the Windows program folder. Is it possible to configure R-Bridge, that not all users need to get these extended rights by i.e. redirecting it to a user profile.

**Comment by scw** [comment]
Hello @albur2018,

By default, R supports two locations it will check for libraries: one in Program Files, and a second within the users profile. The default location for user packages is `%USERPROFILE%\Documents\R\win-library\x.y` where x and y are the major and minor versions, e.g. "3.5" for the current release. If this directory doesn't exist, then it will just try the Program Files location. You can fix this by running this command:

```r
dir.create(Sys.getenv("R_LIBS_USER"), recursive = TRUE)
```
See [further details on the Windows R FAQ](https://cran.r-project.org/bin/windows/base/rw-FAQ.html#I-don_0027t-have-permission-to-write-to-the-R_002d3_002e5_002e1_005clibrary-directory_002e) which provides more details on configuring a per-user library.

Cheers,
Shaun

**Comment by scw** [comment]
I should also note that you can set R_LIBS_USER to any location if you'd prefer to have users store packages in some other location, it just needs to be a user-writable directory for it to work.

**Comment by scw** [comment]
@albur2018 Were you able to resolve the issues installing the bridge in a multiple user configuration?

**Comment by scw** [comment]
@albur2018 I hope the above guidance was able to resolve your issue, if not feel free to open a new one and we can look further.
