### ISSUE TITLE
Rstudio can't find the R binding package

### ISSUE THREAD

**Issue by Nahal2** [R-ArcGIS/r-bridge-install#77]
I use ArcMap 10.3.2 32 bit. I installed R and Rstudio 32 bit. 
When I ran "arc.check_product() in R it showed:
> arc.check_product()
product: ArcGIS Desktop ( 10.3.1.4959 )
license: Advanced 
version: 1.0.1.232 

But when I'm trying to use R Studio I got this:
library(arcgisbinding)
Error in library(arcgisbinding) : 
  there is no package called ‘arcgisbinding’.
Now I'm trying to install again R binding witinh ArcMap, it asked me to select R version.  When I put '32'
I got this:

Executing: InstallBindings false 32
Start Time: Thu Sep 20 17:26:15 2018
Running script InstallBindings...
Updating default R to 32

Traceback (most recent call last):
  File "<string>", line 232, in execute
  File "<string>", line 244, in set_default_r
KeyError: u'32'

Failed to execute (InstallBindings).
Failed at Thu Sep 20 17:26:15 2018 (Elapsed Time: 0.01 seconds)

**Comment by robkemp** [comment]
I saw the same issue using ArcGISPro 2.2. The toolbox requires a version, and trying 3.5.1 or 351 yields this bomb.

**Comment by Nahal2** [comment]
Thank you Shaun. But I’m using ArcMap 10.3.1, 32 bite. This video is for ArcPro.

Nahal

**Comment by scw** [comment]
@Nahal2 Yes, that comment was only for @robkemp's follow-up question. Could you run the "R Installation Details" tool and report its results? The tool examines the registry to find valid R installations, but it seems like it isn't working correctly with the configuration present on your machine, and I'd like to investigate.

**Comment by Nahal2** [comment]
I ran this in R- 32-bit:
> library(arcgisbinding)
*** Please call arc.check_product() to define a desktop license.
Warning message:
package ‘arcgisbinding’ was built under R version 3.5.0 
> arc.check_product()
product: ArcGIS Desktop ( 10.3.1.4959 )
license: Advanced 
version: 1.0.1.232 
> 

Then ran I in R-studio:

 library(arcgisbinding)
> arc.check_product()
Error: Could not bind to a valid ArcGIS Pro installation.
Found ArcGIS Desktop (32-bit) Version 10.3.4959.
You'll need to use the 32-bit version of R.

Thanks

**Comment by scw** [comment]
@Nahal2 For R Studio, you'll need to select a 32-bit version of R from the [preferences pane](https://support.rstudio.com/hc/en-us/articles/200486138-Changing-R-versions-for-RStudio-desktop). 

That should fix the issue with working in R Studio, but if you'd also like to have R work from GP tools, I'd like to dig into why the script is failing. To determine that, could you run the "R Installation Details" tool from the Python toolbox? It should be listed as in below:

![](https://github.com/R-ArcGIS/r-bridge-install/blob/master/img/r-bridge-install-arcmap.png)

**Comment by Nahal2** [comment]
Thank you Shaun 
The 'R installation details' window didn't load. I tried several times.

![r](https://user-images.githubusercontent.com/36236554/46168004-3dda4400-c265-11e8-857b-56f368275a76.png)

**Comment by scw** [comment]
It doesn't display anything on opening the tool, only on running it -- could you click the OK and send back the text it prints out?

**Comment by Nahal2** [comment]
It ran successfully! Thank you Shaun

**Comment by scw** [comment]
@Nahal2 OK, could you share what it reports? That will help me figure out why the Install R bindings tool didn't do what we expected. Thanks!

**Comment by Nahal2** [comment]
![image](https://user-images.githubusercontent.com/36236554/46168591-e9d05f00-c266-11e8-942d-fb1ee203b28f.png)

So, it's done, right?

**Comment by scw** [comment]
@Nahal2 Sorry, missed this earlier. Yes, that all looks normal. I'm not clear why it didn't update the registry correctly on your machine, I'll keep investigating and see if I can reproduce. Thanks for your help, and let us know if you have any other issues with the bridge.
