### ISSUE TITLE
Trouble install R-bridge-install with ArcMAP 10.6.3

### ISSUE THREAD

**Issue by emsa999** [R-ArcGIS/r-bridge-install#78]
Hello,

After following instruction on the github page, I received the error message when I try to install the R bindings:
Executing: InstallBindings true 3.5.1
Start Time: Tue Oct  9 13:14:31 2018
Running script InstallBindings...
Saving URL to 'c:\users\emsa\appdata\local\temp\arca747\tmpgzufk2\arcgisbinding_1.0.1.232.zip'
Rcmd.exe INSTALL c:\users\emsa\appdata\local\temp\arca747\tmpgzufk2\arcgisbinding_1.0.1.232.zip
* installing to library 'C:/Program Files/R/R-3.5.1/library'
Error: ERROR: no permission to install to directory 'C:/Program Files/R/R-3.5.1/library'
In R CMD INSTALL
R command returned non-zero exit status.
Rscript.exe c:\users\emsa\appdata\local\temp\arca747\tmpgzufk2\install.R
Warning in install.packages("c:/users/emsa/appdata/local/temp/arca747/tmpgzufk2/arcgisbinding_1.0.1.232.zip",  :
'lib = "C:/Program Files/R/R-3.5.1/library"' is not writable
Error in install.packages("c:/users/emsa/appdata/local/temp/arca747/tmpgzufk2/arcgisbinding_1.0.1.232.zip",  :
unable to install packages
Execution halted
R command returned non-zero exit status.
Fallback installation method failed.
Completed script InstallBindings...
Succeeded at Tue Oct  9 13:14:35 2018 (Elapsed Time: 3.67 seconds)

I've also tried with arcgisbinding_1.0.1.230.zip since I've read it is for R 3.5, but it has failed too. I am using R3.5.1 i386 (32-bit) as my platform.

**Comment by scw** [comment]
@emsa999 Thanks for reporting your issue. It looks like either this installer isn't picking up your per-user packages directory, or one doesn't exist, can you navigate to `C:\emsa\Documents\R\win-library\3.5` in File Explorer?

The simplest fix is to start ArcMap as administrator -- then it can write to Program Files without issue. The other fix is to create the `C:\emsa\Documents\R\win-library\3.5` directory so it has a per-user location for packages.

**Comment by AysunK15** [comment]
Hi, 
I have ArcGIS 10.5.1 32 bit and R 3.4.3 i386 32 bit. I unpacked arcgicbinding successfully.I tried the troubleshoot options. None of them worked. 
I receive an error like this. 

![arcbinding_error](https://user-images.githubusercontent.com/42001383/49456429-588ee300-f7e9-11e8-8b9d-7fc81b8abc85.JPG)
Thank you.

**Comment by scw** [comment]
@AysunK15 Could you right click on "R Integration.pyt" and select "Show Errors" and report what it says?

I also saw an earlier version of the post with the screenshot of installing from R itself -- that also should work fine, and it looks like it did install but you weren't able to import the package. From that same R session, could you report what the value of `version$arch` is? Thanks!

**Comment by AysunK15** [comment]
@scw The error mesage is: ImportError: DLL load failed: %1 is not a valid Win32 application.

I solved the installing R problem.  I re-run from the R.exe not in R studio. So that problem was solved. By accident I uploaded the screenshot of the error. Thanks.

**Comment by AysunK15** [comment]
@scw The error message is as below. 
![pythonerror](https://user-images.githubusercontent.com/42001383/49506985-ca197080-f87f-11e8-8db1-2c2b19d15cb9.JPG)

I attached the version$arc screenshot as well. 
![arcgisversion](https://user-images.githubusercontent.com/42001383/49506877-87579880-f87f-11e8-8105-653a6e8d48fb.JPG)

Thank you.

**Comment by scw** [comment]
OK, it looks like Python isn't being correctly initialized on your machine -- this may be affecting both ArcMap and the ability for the bindings to connect to R (even though its an R binding, the Geoprocessing framework needs Python for some of its actions). What it looks like is that the Python interpreter that is configured to be the default on your machine is a 64-bit version of Python. This may have happened when installing an additional application which also uses Python, or a standalone Python installation which registered itself as the default. The easiest way to fix this is to run the "Repair" operation on your ArcGIS Desktop installation, which should reconfigure the default 32-bit version of Python that ArcMap ships with. If that doesn't work, let me know.

**Comment by scdub** [comment]
Closing this, a valid Python installation is a requirement for Geoprocessing and running this toolbox -- if the issue persists after an installation repair, we can dig in further.
