### ISSUE TITLE
Error in do.call : subscript out of bounds Failed to execute (Script)

### ISSUE THREAD

**Issue by salauddin81** [R-ArcGIS/r-bridge-install#83]
I am totally zero in programming. I am trying to run a r script in arcgis but it is saying that Error in do.call : subscript out of bounds 
Failed to execute (Script).
What will I do now? Please help me, someone..

**Comment by scdub** [comment]
@salauddin81 If you're still having problems with this, please provide a full script example that we can look at. Unfortunately, working with the R bridge currently does require some level of knowledge of the R programming language.
