### ISSUE TITLE
R not detected

### ISSUE THREAD

**Issue by Vrijsen-E** [R-ArcGIS/r-bridge-install#87]
When I try to 'Install R bindings' in ArcMap, the Selected R Version gives 'R not detected'. The tile is gray. I have R version 3.6.1 installed. What could be the issue and how can I omit this?

![image](https://user-images.githubusercontent.com/56072793/68382801-c14ab200-0154-11ea-8c0b-1dcb0a1c3c4a.png)

**Comment by scdub** [comment]
@Vrijsen-E, the main way that we find R is via the registry. When you install R, there is an option to add it to the registry, and without that setting, we may not be able to detect where R is installed. You can get these entries by reinstalling R and telling it that you'd like to have it set the registry keys, or by manually creating them. For example:

```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\R-core]

[HKEY_LOCAL_MACHINE\SOFTWARE\R-core\R]
"InstallPath"="C:\\Program Files\\R\\R-3.6.1"
"Current Version"="3.6.1"

[HKEY_LOCAL_MACHINE\SOFTWARE\R-core\R\3.6.1]
"InstallPath"="C:\\Program Files\\R\\R-3.6.1"

[HKEY_LOCAL_MACHINE\SOFTWARE\R-core\R64]
"InstallPath"="C:\\Program Files\\R\\R-3.6.1"
"Current Version"="3.6.1"

[HKEY_LOCAL_MACHINE\SOFTWARE\R-core\R64\3.6.1]
"InstallPath"="C:\\Program Files\\R\\R-3.6.1"
```

If you saved that text to an "r.reg" file, and changed the path entries where needed, it should be able to be detected by the script. Alternatively, you can follow the [offline installation](https://github.com/R-ArcGIS/r-bridge-install#offline-installation) instructions which let you install from directly within R.

**Comment by scdub** [comment]
No further updates, closing until we have details.
