### ISSUE TITLE
ArcGIS R package not installed, but it is...

### ISSUE THREAD

**Issue by StumWhere** [R-ArcGIS/r-bridge-install#89]
When running the R Installation Details tool, it reports: 
The ArcGIS R package is not installed. Use the 'Install R Bindings' tool to install it.
But in R I can plainly see that arcgisbinding package is alive and well.
This is because my library is not in C:\Program Files\R\R-3.6.2\library rather under my User profile as it needs to be on our system. The tool needs to search all listed paths via the .libPaths

**Comment by scdub** [comment]
@StumWhere We currently check the library in the install location and additionally in `%USERPROFILE%\Documents\R\win-library\R-x.x`, is your system installing it into another location? If you have a custom location, you can also set the environment variable `R_LIBS_USER` and it should be detected automatically. We are trying to avoid calling R which takes a while to initialize and call `.libPaths()`.

**Comment by scdub** [comment]
@StumWhere we haven't heard back from you about how your R is configured, but if you are still having an issue here we can reopen this and take a look when you're able to provide details.
