### ISSUE TITLE
Why the dependency upon 10.3.1?

### ISSUE THREAD

**Issue by faridcher** [R-ArcGIS/r-bridge-install#9]
Is there anything special with 10.3.1 that R-bridge is dependent on it?
I suppose it can be used in standalone mode(R script). But to make use of geoprocessing framework, 10.3.1 is needed! Am I right?

 I need to use it with 10.2.2.

**Comment by scw** [comment]
Farid,

Lettting ArcGIS know how to appropriately handle R scripts requires changes to the application. Unfortunately, the release of 10.2.2 predates the existence of this project. The actual integration with R can be used however, by [downloading the release](https://github.com/R-ArcGIS/r-bridge/releases/latest)  and manually installing it into R, as shown [in this screencast](https://4326.us/R/zipinst/). That approach, which will give you full access to ArcGIS features from R will work with 10.2.2.

**Comment by faridcher** [comment]
I manually installed R-bridge before. But I get error

```
library(arcgisbinding)
arcgisbinding::arc.check_product()
 

Error in .call_proxy("arc_AoInitialize") : 
  Could not bind to a valid ArcGIS installation

**Comment by scw** [comment]
Unless you've installed Background Geoprocessing, you _must_ be in 32-bit R (the icon is labeled with "i386".

**Comment by faridcher** [comment]
This is great. Thanks
