### ISSUE TITLE
Error in download.file

### ISSUE THREAD

**Issue by wadlooper** [R-ArcGIS/r-bridge-install#90]
I believe the problem is that the install package is apparently not recognizing that I have moved /[user]/Downloads to the D: drive

I've had a similar issue before @ ArcMap which may be related:

https://github.com/R-ArcGIS/r-bridge-install/issues/59

In this case, this install is being performed directly from ArcGIS Pro (2.5) @ Project | Options | Geoprocessing | "Please install the ArcGIS R integration package" 

> install.packages(pkgs='https://github.com/R-ArcGIS/r-bridge/releases/download/v1.0.1.239/arcgisbinding_1.0.1.239.zip',repos=NULL,destdir='C:/Users/[user]/Downloads')

Installing package into 'D:/Users/[user]/Documents/R/win-library/3.5'
(as 'lib' is unspecified)

 Error in download.file(p, destfile, method, mode = "wb", ...) :
cannot open destfile 'C:/Users/[user]/Downloads/arcgisbinding_1.0.1.239.zip', reason 'No such file or directory'

Workaround was to manually download the zipfile and extract it into /Documents/R/win-library/3.5

**Comment by orhuna** [comment]
@wadlooper thanks for reporting is the issue and the workaround. You are right, zip file cannot be located by the installer which extracts the zip into R/win-library/[version]

A potential fix:
Does your PATH environment variable contain D:/[user]/Downloads? Also after moving did you erase C:/[user]/Downloads from it? If yes to both, updating new Downloads in PATH can help fix the problem.

**Comment by wadlooper** [comment]
@orhuna - thanks for your comments, my replies below

>Does your PATH environment variable contain D:/[user]/Downloads?

No

>Also after moving did you erase C:/[user]/Downloads from it?

Did I erase it from PATH? No

The "move" was performed by Windows via /Downloads' Properties Location Tab, changing "C:" to "D:", then selecting the Move button

>If yes to both, updating new Downloads in PATH can help fix the problem.

Possibly, but /Downloads is not in PATH now and likely was not there before

See the Jan 4, 2018 commit by @scw (https://github.com/R-ArcGIS/r-bridge-install/commit/1dcd13c558bd1f26211635f1d1a7780a3f9b6baf) for the previous fix that may be applicable here

**Comment by huanglong161** [comment]
![image](https://user-images.githubusercontent.com/61147257/79044977-1aa29a00-7c3b-11ea-84c9-fc57609a83a3.png)

**Comment by orhuna** [comment]
@wadlooper does this issue still persists?

**Comment by wadlooper** [comment]
@orhuna  sorry for the delayed reply - I assumes that yes it still persists, but I had previously used the workaround described above and since have not attempted to reproduce the error - thanks

**Comment by orhuna** [comment]
Thanks @wadlooper , we will track internally and update here once this is fixed/confirmed.

**Comment by orhuna** [comment]
@wadlooper please try the latest version. I highly recommend switching to ArcGIS Pro 2.6+ as we made updates to R-ArcGIS Bridge installer in the Geoprocessing Tab. Currently, this issue is fixed. Please feel free to reopen if you run into issues.
