### ISSUE TITLE
who can help me？

### ISSUE THREAD

**Issue by huanglong161** [R-ArcGIS/r-bridge-install#91]
![image](https://user-images.githubusercontent.com/61147257/79045059-b03e2980-7c3b-11ea-9e94-d9ef3c62b93d.png)

**Comment by orhuna** [comment]
@huanglong161 please try downloading the zip directly from the R-ArcGIS binding repo. Please follow the offline installation steps [here](https://github.com/R-ArcGIS/r-bridge-install/#offline-installation)

**Comment by orhuna** [comment]
@huanglong161 , does the issue still persist?

**Comment by huanglong161** [comment]
Thanks, it has been solved


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Orhun"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月5日(星期二) 凌晨1:50
收件人:&nbsp;"R-ArcGIS/r-bridge-install"<r-bridge-install@noreply.github.com&gt;;
抄送:&nbsp;"黄龙"<525422032@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [R-ArcGIS/r-bridge-install] who can help me？ (#91)





 
@huanglong161 , does the issue still persist?
