### ISSUE TITLE
what this mean？

### ISSUE THREAD

**Issue by huanglong161** [R-ArcGIS/r-bridge-install#92]
![image](https://user-images.githubusercontent.com/61147257/79176205-2f954e00-7e32-11ea-9cbb-338dc6297083.png)

**Comment by orhuna** [comment]
@huanglong161 , this is a character parsing issue that `bootstrap_r.py` encounters when trying to get the install path and install the arcgisbinding onto that path. This is a commonly encountered problem for Python 2.x on different i18n.

For the purposes of installing the bridge, can you please try copying the `arcgisbinding` folderdirectly onto the R package directory? You can find the steps [here](https://github.com/R-ArcGIS/r-bridge-install/).

**Comment by orhuna** [comment]
Hello @huanglong161 . Does the issue still persist?

**Comment by huanglong161** [comment]
Thanks, it has been solved




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Orhun"<notifications@github.com&gt;; 
发送时间: 2020年5月5日(星期二) 凌晨1:50
收件人: "R-ArcGIS/r-bridge-install"<r-bridge-install@noreply.github.com&gt;; 
抄送: "黄龙"<525422032@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [R-ArcGIS/r-bridge-install] what this mean？ (#92)





 
Hello @huanglong161 . Does the issue still persist?
 
&mdash;
