### ISSUE TITLE
Installation in R 4.0.0

### ISSUE THREAD

**Issue by bltern** [R-ArcGIS/r-bridge-install#93]
Hi,
I previously had this installed and running with ArcGIS Pro 2.4 and R 3.5.3. I recently installed 4.0.0 and it installs and finds 4.0.0 in ArcGIS Pro, but gives this error when trying to load the library in R:

Error: package or namespace load failed for ‘arcgisbinding’:
 package ‘arcgisbinding’ was installed before R 4.0.0: please re-install it

I have updated the bindings and even reinstalled R 4.0, but have not managed to get the package to load. Can you confirm if this will work (or not) with R 4.0.0.  If not, I'll revert to an earlier R. 

Cheers, Andrew

**Comment by orhuna** [comment]
Hello @bltern . 

Support for `arcgisbinding` for  `R 4.0.0` is under active development. As the package binding mechanism is different between 4.0.0 and previous R versions, we will be updating our installation routine.

Converting this to a question issue to keep you updated once the new version is out.

**Comment by bltern** [comment]
Thanks for the info. I will watch for the update.

**Comment by Nova-Scotia** [comment]
In the meantime, do we have to use R 3.5 to use the package?

**Comment by orhuna** [comment]
@bltern , you can set up `arcgisbindin` for R 4.0 by using running the script below in the R Console:

`install.packages("arcgisbinding", repos="http://r-arcgis.github.io/r-bridge", type="win.binary")`

**Comment by orhuna** [comment]
@Nova-Scotia you can now use the latest version of R, `arcgisbinding` now plays nicely with R 4.0. You can use the script below to setup the R-Bridge on R 4.0

`install.packages("arcgisbinding", repos="http://r-arcgis.github.io/r-bridge", type="win.binary")` 

The issue you are running into pertains to change of dlls and addition of new dynamic libraries with new versions of R. When any package is setup with a new version of R some back-compatibility issues are observed. If you would like to use `R 3.5.x` in conjunction with `R 4.0.x`, [this thread](https://github.com/r-lib/rlang/issues/416#issuecomment-370995008) might be useful. 

Please reach out if this issue persists.

**Comment by bltern** [comment]
@orhuna Thanks for the update. Great news, that worked fine.

**Comment by Nova-Scotia** [comment]
@orhuna yes!! Thank you, so many of my newer scripts rely on this package, wonderful to have a quick fix. Love being able to grab stuff from arc and arc online and use it in R - so seamless. Really appreciate you taking the time to update us!

**Comment by orhuna** [comment]
Great to hear @bltern and @Nova-Scotia ! Closing this issue.

**Comment by fgoerlich** [comment]
Does this works for ArcGIS 10.6 (32 bits)?

**Comment by orhuna** [comment]
@fgoerlich this only works for 64-bit.

**Comment by pyacobellis** [comment]
hi Orhuna - thanks for the help.   Are there plans sync  the arcgisbinding package (R 4.0) with ArcGIS 10.6 (32-bit)?

If not, how do I upgrade to 64-bit.

**Comment by dpavlushko** [comment]
I just uploaded full (Desktop 32 bit and Pro 64-bit) version of the package. 
Run this command to install `arcgisbinging` package for R 4.0
```R
install.packages("arcgisbinding", repos="http://r-arcgis.github.io/r-bridge", type="win.binary")
```
@pyacobellis If you can switch to ArcGIS Pro it is native 64-bit version.

**Comment by fgoerlich** [comment]
@dpavlushko Thanks. It works from R, but I still face this issue: #94
