### ISSUE TITLE
Unable to install r-bridge

### ISSUE THREAD

**Issue by seyoumyg** [R-ArcGIS/r-bridge-install#94]
I am trying to install r-bridge on ArcGIS 10.5 but Install R Bindings throws back this error:
Executing: InstallBindings false 3.3.2
Start Time: Thu May 07 08:33:29 2020
Running script InstallBindings...
Updating default R to 3.3.2

Traceback (most recent call last):
  File "<string>", line 232, in execute
  File "<string>", line 244, in set_default_r
KeyError: u'3.3.2'

Failed to execute (InstallBindings).
Failed at Thu May 07 08:33:29 2020 (Elapsed Time: 0.01 seconds)

**Comment by seyoumyg** [comment]
![Error](https://user-images.githubusercontent.com/64976971/81319900-37b56780-9045-11ea-91e3-ef6c46f827b0.PNG)
![R_installation](https://user-images.githubusercontent.com/64976971/81319936-43a12980-9045-11ea-930d-0d24a207fb62.PNG)
![R_print](https://user-images.githubusercontent.com/64976971/81319941-46038380-9045-11ea-8a62-324dae7ff51c.PNG)

**Comment by fgoerlich** [comment]
I have exactly the same problem with ArcGIS version 10.6 and R version 4.0.0

**Comment by fgoerlich** [comment]
![Problem01](https://user-images.githubusercontent.com/6486324/83124909-1b9e6680-a0d7-11ea-8b12-4931d703dc8f.png)

**Comment by orhuna** [comment]
@seyoumyg @fgoerlich we released a version of `arcgisbinding` that now has different installers for R 3.x and 4.x. This is under the hood and addresses issues with 3.6 and 4.x. Please let us know if this issue persists.
