### ISSUE TITLE
Link to R-repository broken

### ISSUE THREAD

**Issue by GDoerffel65** [R-ArcGIS/r-bridge-install#95]
Hi, them link to the r-repository in the prerequisits section of the readme is broken: Berkley does not allow off-campus access anymore. Another CRAN mirror should be referenced here

**Comment by scdub** [comment]
Thanks for the report! Should be fixed with https://github.com/R-ArcGIS/r-bridge-install/commit/074650348ed6cd467d346dece3739412a73ccf89
