### ISSUE TITLE
More link issues

### ISSUE THREAD

**Issue by GDoerffel65** [R-ArcGIS/r-bridge-install#96]
Hi,
the ReadMe has more link issues:
1)
![image](https://user-images.githubusercontent.com/37537171/84116875-eed04480-aa30-11ea-80f6-1016481030cd.png) - the sample tools link (twice in the doc) is dead. Assume this is supposed to be https://github.com/R-ArcGIS/r-sample-tools ...
2) The GeoNet community page ... is this what is supposed to be linked here:
![image](https://user-images.githubusercontent.com/37537171/84117181-63a37e80-aa31-11ea-94b8-b700b40b58f1.png)

Regards
Guenter

**Comment by orhuna** [comment]
@GDoerffel65 Thanks again for reporting this issue. I am working on reproducing your workflow and will touch base once the sentinal workflow is done with R-ArcGIS Bridge.

**Comment by scdub** [comment]
Hello Guenter,

This issue should be resolved with b2772b4

Thanks for reporting it!
