### ISSUE TITLE
Export to Geodatabase Error

### ISSUE THREAD

**Issue by MBollinger89** [R-ArcGIS/r-bridge-install#97]
I was able to install r-bridge with no issue and have used it to export this geodatabase in the past. Currently I am getting this error "Error in .call_proxy("arc_write", path, pairlist(data = data, coords = coords,  : 
  insert row failed".
I am running on R version 3.6.1 with arcgisbinding version 1.0.1.241 and am trying to export a 300,000 line spatial point data frame to an arc geodatabase. Using arc.write(path = "path", data = spdf, overwrite = T).

**Comment by orhuna** [comment]
@MBollinger89 thanks for this report. What is the type of spdf? Is it sf or sp?

**Comment by orhuna** [comment]
@MBollinger89 not sure if this issue persists. We updated arcgisbinding, v244, to work in full compliance with the latest sf and sp packages. Please update and feel free to reopen the issue if the issue persists.

**Comment by MBollinger89** [comment]
It was built with sp. I'm not sure if the issue persits at the moment, I built a work around to use instead of the geodatabase. I'll test the workflow with the new version and report if the issue persists. Thanks for the fix.
