### ISSUE TITLE
'arcgisbinding’ is not available for R version 4.0.2 ?

### ISSUE THREAD

**Issue by Guibi1994** [R-ArcGIS/r-bridge-install#99]
Hi!, I'm trying to install the "arcgisbinding" in Microsoft R, but it seems that is not available for my current version of R.
This is the message it is showing:

Warning in install.packages :
  package ‘arcgisbinding’ is not available (for R version 4.0.2)

What could I do in order to install the library?

I really appreciate any help you can provide.

**Comment by scdub** [comment]
@Guibi1994 Unfortunately this installer doesn't detect MRO installations. You can manually install into MRO by running this command from your R session:

```R
install.packages("arcgisbinding", repos="http://r.esri.com", type="win.binary")
```
